[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "cd ydt-kelime-pratigi && npm install --include=dev"
]

[phases.build]
cmds = ["cd ydt-kelime-pratigi && npx vite build"]

[start]
cmd = "node server.js"
