const wordsData = [

  { term: "accelerate", meaning: "hızlandırmak, ivme kazandırmak", hint: "to cause to move faster", example: "The car began to accelerate down the hill.", level: "C1" },
  { term: "affect", meaning: "etkilemek", hint: "to have an influence on", example: "The bad weather will affect our plans.", level: "B2" },
  { term: "allocate", meaning: "tahsis etmek, ayırmak", hint: "to distribute for a specific purpose", example: "We need to allocate more funds to the education budget.", level: "C1" },
  { term: "allow", meaning: "izin vermek, olanak tanımak", hint: "to give permission", example: "They don't allow smoking in this building.", level: "A2" },
  { term: "alter", meaning: "değiştirmek, değişmek", hint: "to make or become different", example: "She had to alter her clothes after losing weight.", level: "B2" },
  { term: "ambiguous", meaning: "belirsiz, iki anlama gelebilen", hint: "open to more than one interpretation", example: "The politician gave an ambiguous answer to the question.", level: "C2" },
  { term: "approve", meaning: "onaylamak", hint: "to officially agree to", example: "The board will approve the new strategy next week.", level: "B2" },
  { term: "attract", meaning: "cezbetmek, çekmek", hint: "to cause to come to a place", example: "The new mall will attract many shoppers.", level: "B1" },
  { term: "available", meaning: "mevcut, ulaşılabilir", hint: "ready for use", example: "Are there any tickets available for tonight?", level: "A2" },
  { term: "bias", meaning: "ön yargı, eğilim", hint: "prejudice in favor of or against one thing", example: "There was a clear bias toward the local candidate.", level: "C1" },
  { term: "burden", meaning: "yük, külfet", hint: "a heavy load or responsibility", example: "I don't want to be a burden to my family.", level: "C1" },
  { term: "by", meaning: "tarafından, -erek", hint: "indicates the agent performing an action", example: "The book was written by him.", level: "A1" },
  { term: "cause", meaning: "sebep olmak", hint: "to make something happen", example: "What was the main cause of the accident?", level: "B1" },
  { term: "challenge", meaning: "zorluk, meydan okuma", hint: "a difficult task", example: "Learning a new language is a fun challenge.", level: "B1" },
  { term: "coherent", meaning: "tutarlı, mantıklı", hint: "logical and consistent", example: "He failed to provide a coherent explanation.", level: "C1" },
  { term: "confine", meaning: "sınırlandırmak, hapsetmek", hint: "to restrict within certain limits", example: "Please confine your discussion to the main topic.", level: "C2" },
  { term: "conflict", meaning: "çatışma, anlaşmazlık", hint: "a serious disagreement", example: "There is a long-standing conflict between the two nations.", level: "B2" },
  { term: "consume", meaning: "tüketmek", hint: "to use up", example: "These old cars consume a lot of gas.", level: "B1" },
  { term: "convenience", meaning: "kolaylık", hint: "the state of being able to proceed with little effort", example: "I like the convenience of living near the station.", level: "B2" },
  { term: "convincing", meaning: "ikna edici", hint: "capable of causing belief", example: "She made a convincing argument for the changes.", level: "B2" },
  { term: "create", meaning: "yaratmak, oluşturmak", hint: "to bring into existence", example: "We can create a new file for this project.", level: "A2" },
  { term: "crucial", meaning: "çok önemli, kritik", hint: "decisive or critical", example: "Water is crucial for survival.", level: "B2" },
  { term: "define", meaning: "tanımlamak", hint: "to state the meaning of", example: "How would you define success?", level: "B2" },
  { term: "delicate", meaning: "narin, hassas", hint: "easily broken or damaged", example: "The glasses are very delicate, so handle them carefully.", level: "C1" },
  { term: "deny", meaning: "inkar etmek", hint: "to state that something is not true", example: "He didn't deny breaking the window.", level: "B2" },
  { term: "destroy", meaning: "yok etmek", hint: "to damage beyond repair", example: "The fire will destroy the entire forest if not stopped.", level: "B1" },
  { term: "detect", meaning: "tespit etmek", hint: "to discover the presence of", example: "The machine can detect even small amounts of poison.", level: "C1" },
  { term: "determine", meaning: "belirlemek", hint: "to figure out or decide", example: "The test will determine your English level.", level: "B2" },
  { term: "develop", meaning: "geliştirmek", hint: "to grow or cause to grow", example: "She wants to develop her programming skills.", level: "B1" },
  { term: "distract", meaning: "dikkatini dağıtmak", hint: "to draw attention away", example: "Don't let the music distract you from studying.", level: "B2" },
  { term: "division", meaning: "bölünme, kısım", hint: "the act of separating something into parts", example: "The division of the company into two branches was successful.", level: "B2" },
  { term: "drastic", meaning: "şiddetli, radikal", hint: "likely to have a strong effect", example: "The company had to take drastic measures to survive.", level: "C1" },
  { term: "drawback", meaning: "dezavantaj, eksiklik", hint: "a disadvantage or problem", example: "The main drawback of the plan is its high cost.", level: "C1" },
  { term: "elaborate", meaning: "detaylı, ayrıntılı", hint: "involving many careful details", example: "They made elaborate preparations for the wedding.", level: "C2" },
  { term: "eliminate", meaning: "ortadan kaldırmak", hint: "to completely remove", example: "Dieting helps eliminate toxins from the body.", level: "C1" },
  { term: "encompass", meaning: "kapsamak", hint: "to include comprehensively", example: "The course will encompass all aspects of business management.", level: "C2" },
  { term: "enhance", meaning: "geliştirmek, artırmak", hint: "to improve the quality of", example: "Adding spices will enhance the flavor of the dish.", level: "C1" },
  { term: "establish", meaning: "kurmak", hint: "to set up on a firm basis", example: "The business was established in 1990.", level: "B2" },
  { term: "evaluate", meaning: "değerlendirmek", hint: "to form an idea of the value of", example: "Teachers evaluate students' progress through tests.", level: "C1" },
  { term: "evidence", meaning: "kanıt", hint: "facts indicating whether something is true", example: "There is no evidence to support his claim.", level: "B2" },
  { term: "excessive", meaning: "aşırı", hint: "more than is necessary", example: "Excessive drinking can damage your liver.", level: "C1" },
  { term: "expect", meaning: "beklemek, ummak", hint: "to regard as likely to happen", example: "I expect him to arrive late.", level: "B1" },
  { term: "experience", meaning: "deneyimlemek", hint: "to encounter or undergo", example: "You will experience different cultures while traveling.", level: "B1" },
  { term: "explore", meaning: "keşfetmek", hint: "to travel through to learn about", example: "We decided to explore the old city center.", level: "B1" },
  { term: "flourish", meaning: "gelişmek, serpilmek", hint: "to grow vigorously", example: "These plants flourish in damp environments.", level: "C2" },
  { term: "harmful", meaning: "zararlı", hint: "causing damage", example: "Smoking is harmful to your health.", level: "B1" },
  { term: "hinder", meaning: "engellemek", hint: "to create difficulties", example: "A poor diet can hinder your athletic performance.", level: "C2" },
  { term: "impact", meaning: "etki", hint: "a marked influence", example: "The new law will have a huge impact on small businesses.", level: "B2" },
  { term: "implication", meaning: "ima, olası sonuç", hint: "a conclusion that can be drawn", example: "The implication is that he was lying.", level: "C1" },
  { term: "important", meaning: "önemli", hint: "of great significance", example: "It is important to eat healthy food.", level: "A1" },
  { term: "include", meaning: "içermek", hint: "to contain as part of a whole", example: "The price will include tax.", level: "A2" },
  { term: "increase", meaning: "artırmak", hint: "to make greater in size", example: "We need to increase our sales this year.", level: "B1" },
  { term: "indicate", meaning: "işaret etmek, göstermek", hint: "to point out", example: "The dark clouds indicate rain.", level: "B2" },
  { term: "influence", meaning: "etkilemek", hint: "to have an effect on", example: "Parents often influence their children's choices.", level: "B2" },
  { term: "inherit", meaning: "miras almak", hint: "to receive from an ancestor", example: "She will inherit the family business.", level: "C2" },
  { term: "inquiry", meaning: "soruşturma, inceleme", hint: "an act of asking for information", example: "The police launched an inquiry into the murder.", level: "B2" },
  { term: "manipulate", meaning: "yönlendirmek, idare etmek", hint: "to handle or control skillfully", example: "He knows how to manipulate the media.", level: "C2" },
  { term: "modify", meaning: "değiştirmek, uyarlamak", hint: "to make minor changes to", example: "We can modify the design to suit your needs.", level: "B2" },
  { term: "mutual", meaning: "karşılıklı, ortak", hint: "held in common by two or more parties", example: "The agreement is based on mutual respect.", level: "C1" },
  { term: "objective", meaning: "amaç, hedef", hint: "a thing aimed at", example: "Her main objective is to pass the exam.", level: "B2" },
  { term: "obtain", meaning: "elde etmek", hint: "to get or acquire", example: "You must obtain permission to enter.", level: "B2" },
  { term: "partial", meaning: "kısmi", hint: "existing only in part", example: "The operation was a partial success.", level: "C1" },
  { term: "predict", meaning: "tahmin etmek", hint: "to say what will happen in the future", example: "It is hard to predict the weather accurately.", level: "B1" },
  { term: "progress", meaning: "ilerleme", hint: "forward movement", example: "We are making good progress on the project.", level: "B2" },
  { term: "propose", meaning: "önermek", hint: "to put forward a plan", example: "I propose that we start the meeting now.", level: "B2" },
  { term: "protect", meaning: "korumak", hint: "to keep safe", example: "You should protect your skin from the sun.", level: "B1" },
  { term: "provide", meaning: "sağlamak", hint: "to make available", example: "The school will provide all necessary books.", level: "B1" },
  { term: "pure", meaning: "saf", hint: "not mixed with anything else", example: "This ring is made of pure gold.", level: "B2" },
  { term: "reduce", meaning: "azaltmak", hint: "to make smaller", example: "You should try to reduce your sugar intake.", level: "B1" },
  { term: "relation", meaning: "ilişki, bağ", hint: "the way in which things are connected", example: "Is there any relation between diet and health?", level: "B1" },
  { term: "research", meaning: "araştırma yapmak", hint: "to investigate systematically", example: "They will research the effects of the virus.", level: "B1" },
  { term: "resist", meaning: "direnmek", hint: "to withstand the effect of", example: "I couldn't resist eating the cake.", level: "C1" },
  { term: "respond", meaning: "yanıt vermek", hint: "to reply", example: "She didn't respond to my emails.", level: "B2" },
  { term: "responsible", meaning: "sorumlu", hint: "having an obligation to do something", example: "Who is responsible for this mess?", level: "B1" },
  { term: "solution", meaning: "çözüm", hint: "a means of solving a problem", example: "We need to find a solution fast.", level: "B1" },
  { term: "solve", meaning: "çözmek", hint: "to find an answer to", example: "Can you solve this math problem?", level: "B1" },
  { term: "surround", meaning: "çevrelemek", hint: "to be all around", example: "Tall trees surround the house.", level: "B2" },
  { term: "suspend", meaning: "askıya almak", hint: "to temporarily prevent from continuing", example: "They had to suspend the game due to rain.", level: "C1" },
  { term: "swift", meaning: "hızlı", hint: "happening quickly", example: "The government took swift action.", level: "C1" },
  { term: "transmit", meaning: "iletmek", hint: "to pass on from one place to another", example: "The disease is transmitted by mosquitoes.", level: "C1" },
  { term: "uncover", meaning: "ortaya çıkarmak", hint: "to discover something secret", example: "The investigation uncovered a large fraud.", level: "C1" },
  { term: "vague", meaning: "belirsiz", hint: "unclear in meaning", example: "He gave a vague answer to the question.", level: "C1" },
  { term: "vigorous", meaning: "enerjik, güçlü", hint: "strong and full of energy", example: "She does vigorous exercise every morning.", level: "C2" },
  { term: "zealous", meaning: "şevkli, gayretli", hint: "showing strong and energetic support", example: "He is a zealous supporter of the team.", level: "C2" },
  { term: "abandon", meaning: "terk etmek", hint: "to leave a place, thing, or person", example: "They had to abandon the sinking ship.", level: "B1" },
  { term: "bizarre", meaning: "tuhaf, garip", hint: "very strange or unusual", example: "She wore a bizarre outfit to the party.", level: "B2" },
  { term: "cease", meaning: "durdurmak, sona ermek", hint: "to bring or come to an end", example: "The factory will cease operations next month.", level: "C1" },
  { term: "dedicate", meaning: "adamak", hint: "to give all of your energy, time, etc.", example: "He decided to dedicate his life to science.", level: "B2" },
  { term: "emerge", meaning: "ortaya çıkmak", hint: "to become known or apparent", example: "New facts began to emerge after the investigation.", level: "B2" },
  { term: "facilitate", meaning: "kolaylaştırmak", hint: "to make an action or process easier", example: "The new software will facilitate faster data processing.", level: "C1" },
  { term: "generate", meaning: "üretmek, oluşturmak", hint: "to cause something to exist", example: "Wind turbines generate electricity.", level: "B2" },
  { term: "hesitate", meaning: "tereddüt etmek", hint: "to pause before doing something", example: "Don't hesitate to call if you need help.", level: "B2" },
  { term: "ignorance", meaning: "cehalet, bilgisizlik", hint: "lack of knowledge or information", example: "His ignorance of the law was no excuse.", level: "C1" },
  { term: "jump", meaning: "zıplamak, atlamak", hint: "to push yourself suddenly off the ground", example: "The cat can jump very high.", level: "A1" },
  { term: "justify", meaning: "haklı çıkarmak, savunmak", hint: "to show or prove to be right", example: "How can you justify such bad behavior?", level: "B2" },
  { term: "keen", meaning: "hevesli, keskin", hint: "highly developed or very interested", example: "She is a keen reader of historical novels.", level: "B2" },
  { term: "liberate", meaning: "özgürleştirmek", hint: "to set free from a situation", example: "The army fought to liberate the city.", level: "C2" },
  { term: "maintain", meaning: "sürdürmek, korumak", hint: "to keep in an existing state", example: "It is important to maintain a healthy diet.", level: "B2" },
  { term: "negotiate", meaning: "müzakere etmek", hint: "to try to reach an agreement", example: "They need to negotiate a new contract.", level: "C1" },
  { term: "overcome", meaning: "üstesinden gelmek", hint: "to succeed in dealing with a problem", example: "She managed to overcome her fear of flying.", level: "B2" },
  { term: "persuade", meaning: "ikna etmek", hint: "to convince someone to do or believe something", example: "I tried to persuade him to stay.", level: "B2" },
  { term: "quote", meaning: "alıntı yapmak", hint: "to repeat the exact words spoken or written", example: "He likes to quote famous philosophers.", level: "B1" },
  { term: "reluctant", meaning: "isteksiz", hint: "unwilling and hesitant", example: "She was reluctant to leave her hometown.", level: "C1" },
  { term: "sacrifice", meaning: "feda etmek", hint: "to give up something valued", example: "Parents often sacrifice a lot for their children.", level: "B2" },
  { term: "tackle", meaning: "ele almak, çözmeye çalışmak", hint: "to make determined efforts to deal with a problem", example: "The government must tackle the housing crisis.", level: "B2" },
  { term: "undergo", meaning: "geçirmek, maruz kalmak", hint: "to experience something that is necessary", example: "The building will undergo extensive renovations.", level: "C1" },
  { term: "verify", meaning: "doğrulamak", hint: "to make sure that something is true", example: "Please verify your email address to continue.", level: "C1" },
  { term: "wander", meaning: "gezinmek, dolaşmak", hint: "to walk around slowly in a relaxed way", example: "We spent the afternoon wandering around the old town.", level: "B1" },
  { term: "yield", meaning: "ürün vermek, boyun eğmek", hint: "to produce or provide", example: "The new methods should yield better results.", level: "C1" },
  { term: "advocate", meaning: "savunmak, desteklemek", hint: "to publicly recommend or support", example: "She is a strong advocate for animal rights.", level: "C1" },
  { term: "clarify", meaning: "açıklığa kavuşturmak", hint: "to make a statement less confusing", example: "Could you clarify what you mean by that?", level: "B2" },
  { term: "devote", meaning: "adamak, tahsis etmek", hint: "to give all of something, especially your time", example: "He wants to devote more time to his hobbies.", level: "B2" },
  { term: "expand", meaning: "genişletmek, büyütmek", hint: "to become or make larger", example: "The company plans to expand its operations.", level: "B1" },
  { term: "forbid", meaning: "yasaklamak", hint: "to refuse to allow", example: "The law strictly forbids selling alcohol to minors.", level: "B2" },
  { term: "grasp", meaning: "kavramak, anlamak", hint: "to understand something, especially something difficult", example: "It took him a while to grasp the concept.", level: "B2" },
  { term: "hazard", meaning: "tehlike, risk", hint: "a danger or risk", example: "Polluted water is a serious health hazard.", level: "C1" },
  { term: "illustrate", meaning: "örneklerle açıklamak", hint: "to explain or make clear using examples", example: "Let me give an example to illustrate my point.", level: "B2" },
  { term: "kneel", meaning: "diz çökmek", hint: "to fall or rest on the knees", example: "You must kneel when the queen enters.", level: "B2" },
  { term: "migrate", meaning: "göç etmek", hint: "to move from one region or habitat to another", example: "These birds migrate to Africa in winter.", level: "B2" },
  { term: "notorious", meaning: "kötü şöhretli", hint: "famous or well known, typically for some bad quality", example: "The city is notorious for its terrible traffic.", level: "C1" },
  { term: "overlap", meaning: "örtüşmek, üst üste gelmek", hint: "to extend over so as to cover partly", example: "My vacation and yours overlap by two days.", level: "C1" },
  { term: "postpone", meaning: "ertelemek", hint: "to arrange for something to take place at a later time", example: "They had to postpone the meeting due to illness.", level: "B1" },
  { term: "qualify", meaning: "hak kazanmak, yeterlik almak", hint: "to be entitled to a particular benefit", example: "You need to pass the exam to qualify for the certificate.", level: "B1" },
  { term: "rational", meaning: "mantıklı, rasyonel", hint: "based on or in accordance with reason or logic", example: "We need to make a rational decision, not an emotional one.", level: "C1" },
  { term: "scatter", meaning: "dağıtmak, saçmak", hint: "to throw in various random directions", example: "The wind scattered the leaves all over the yard.", level: "B2" },
  { term: "thrill", meaning: "heyecanlandırmak", hint: "a sudden feeling of excitement", example: "Winning the championship gave the team a huge thrill.", level: "B2" },
  { term: "vanish", meaning: "gözden kaybolmak, yok olmak", hint: "to disappear suddenly and completely", example: "The magician made the coin vanish into thin air.", level: "B2" },
  { term: "weird", meaning: "tuhaf, acayip", hint: "suggesting something supernatural; uncanny", example: "I heard a weird noise coming from the basement.", level: "B1" },
  { term: "yell", meaning: "bağırmak", hint: "to shout in a loud, sharp way", example: "There's no need to yell, I can hear you.", level: "B1" },
  { term: "zip", meaning: "fermuarını çekmek, hızlıca gitmek", hint: "to fasten with a zipper", example: "Make sure you zip up your jacket, it's cold outside.", level: "A2" },
  { term: "abundant", meaning: "bol, bereketli", hint: "existing or available in large quantities", example: "Rainfall is abundant in this region.", level: "C1" },
  { term: "barely", meaning: "zar zor, ancak", hint: "only just; almost not", example: "She spoke so quietly that I could barely hear her.", level: "B1" },
  { term: "collide", meaning: "çarpışmak", hint: "to hit with force when moving", example: "Two trains collided in the heavy fog.", level: "C1" },
  { term: "dilemma", meaning: "ikilem, çıkmaz", hint: "a situation in which a difficult choice has to be made", example: "I am in a dilemma about whether to take the job or not.", level: "B2" },
  { term: "adapt", meaning: "uyum sağlamak", hint: "to make suitable to requirements or conditions", example: "It took him a while to adapt to the new work environment.", level: "B2" },
  { term: "acquire", meaning: "edinmek, kazanmak", hint: "to buy or obtain for oneself", example: "The company plans to acquire a smaller competitor.", level: "B2" },
  { term: "acknowledge", meaning: "kabul etmek, onaylamak", hint: "to accept or admit the existence or truth of", example: "He refused to acknowledge his mistake.", level: "C1" },
  { term: "boost", meaning: "artırmak, desteklemek", hint: "to help or encourage to increase or improve", example: "The new advertising campaign should boost sales.", level: "B2" },
  { term: "boundary", meaning: "sınır, hudut", hint: "a line that marks the limits of an area", example: "The river forms the boundary between the two countries.", level: "C1" },
  { term: "brutal", meaning: "acımasız, vahşi", hint: "savagely violent", example: "The weather was brutal during the climb.", level: "C1" },
  { term: "compile", meaning: "derlemek, toplamak", hint: "to produce by assembling information collected from other sources", example: "She took years to compile the dictionary.", level: "C1" },
  { term: "consent", meaning: "rıza, onay", hint: "permission for something to happen or agreement to do something", example: "You cannot proceed without their written consent.", level: "C1" },
  { term: "cultivate", meaning: "yetiştirmek, geliştirmek", hint: "to prepare and use land for crops or gardening", example: "They try to cultivate a good relationship with their clients.", level: "C1" },
  { term: "deceive", meaning: "kandırmak, aldatmak", hint: "to cause someone to believe something that is not true", example: "He tried to deceive his parents about his grades.", level: "C1" },
  { term: "deter", meaning: "caydırmak", hint: "to discourage someone from doing something", example: "High prices deter many young people from buying houses.", level: "C2" },
  { term: "dismiss", meaning: "kovmak, reddetmek", hint: "to order or allow to leave; send away", example: "The manager decided to dismiss the idea entirely.", level: "C1" },
  { term: "enforce", meaning: "uygulamak, zorlamak", hint: "to compel observance of or compliance with a law or rule", example: "It is the police's job to enforce the law.", level: "C1" },
  { term: "exclude", meaning: "hariç tutmak, dışlamak", hint: "to deny someone access to or bar from a place or group", example: "The price of the holiday excludes flights.", level: "B2" },
  { term: "exploit", meaning: "sömürmek, faydalanmak", hint: "to make full use of and derive benefit from a resource", example: "We need to exploit the wind energy potential here.", level: "B2" },
  { term: "fluent", meaning: "akıcı", hint: "able to express oneself easily and articulately", example: "She is fluent in both English and French.", level: "B2" },
  { term: "fluctuate", meaning: "dalgalanmak, değişmek", hint: "to rise and fall irregularly in number or amount", example: "Vegetable prices fluctuate according to the season.", level: "C1" },
  { term: "fragile", meaning: "kırılgan, hassas", hint: "easily broken or damaged", example: "Be careful with that box; the contents are fragile.", level: "C1" },
  { term: "genuine", meaning: "gerçek, hakiki", hint: "truly what something is said to be; authentic", example: "If it is a genuine painting, it will sell for millions.", level: "B2" },
  { term: "gloomy", meaning: "kasvetli, karamsar", hint: "dark or poorly lit, especially so as to appear depressing", example: "It was a wet and gloomy day.", level: "C1" },
  { term: "guarantee", meaning: "garanti etmek, güvence", hint: "a formal promise or assurance", example: "I can't guarantee that the task will be finished today.", level: "B2" },
  { term: "harsh", meaning: "sert, acımasız", hint: "cruel or severe", example: "The children had a harsh upbringing.", level: "B2" },
  { term: "hostile", meaning: "düşmanca, saldırgan", hint: "unfriendly; antagonistic", example: "The crowd received the speaker with hostile remarks.", level: "C1" },
  { term: "implement", meaning: "uygulamak, yerine getirmek", hint: "to put into effect", example: "The government failed to implement the new policy.", level: "B2" },
  { term: "isolate", meaning: "izole etmek, soyutlamak", hint: "to cause a person or place to be or remain alone", example: "They try to isolate the virus in the lab.", level: "B2" },
  { term: "inevitable", meaning: "kaçınılmaz", hint: "certain to happen; unavoidable", example: "With more cars on the road, traffic jams are inevitable.", level: "C1" },
  { term: "judicial", meaning: "yargısal, hukuki", hint: "of, by, or appropriate to a court or judge", example: "The judicial system needs major reforms.", level: "C2" },
  { term: "jurisdiction", meaning: "yargı yetkisi", hint: "the official power to make legal decisions and judgments", example: "This matter falls outside our jurisdiction.", level: "C2" },
  { term: "legacy", meaning: "miras, bırakıt", hint: "an amount of money or property left to someone in a will", example: "He left a powerful legacy of peace and tolerance.", level: "C1" },
  { term: "legitimate", meaning: "yasal, meşru", hint: "conforming to the law or to rules", example: "She has a legitimate reason for being late.", level: "C1" },
  { term: "mandatory", meaning: "zorunlu", hint: "required by law or rules; compulsory", example: "Wearing seatbelts is mandatory in this state.", level: "B2" },
  { term: "merge", meaning: "birleşmek, kaynaşmak", hint: "to combine or cause to combine to form a single entity", example: "The two banks decided to merge last year.", level: "B2" },
  { term: "neglect", meaning: "ihmal etmek", hint: "to fail to care for properly", example: "He tends to neglect his health when he is stressed.", level: "B2" },
  { term: "numerous", meaning: "çok sayıda", hint: "great in number; many", example: "She has won numerous awards for her acting.", level: "B1" },
  { term: "obscure", meaning: "anlaşılması güç, belirsiz", hint: "not discovered or known about; uncertain", example: "The origins of the tradition are obscure.", level: "C1" },
  { term: "obsolete", meaning: "modası geçmiş, eskimiş", hint: "no longer produced or used; out of date", example: "Typewriters have become obsolete due to computers.", level: "C1" },
  { term: "perceive", meaning: "algılamak, sezmek", hint: "to become aware or conscious of something", example: "Cats are not able to perceive color as well as humans.", level: "B2" },
  { term: "persist", meaning: "ısrar etmek, devam etmek", hint: "to continue firmly or obstinately", example: "If the symptoms persist, consult a doctor.", level: "C1" },
  { term: "quit", meaning: "bırakmak, çıkmak", hint: "to leave, usually permanently", example: "He decided to quit his job and travel the world.", level: "B1" },
  { term: "queue", meaning: "sıra, kuyruk", hint: "a line or sequence of people or vehicles awaiting their turn", example: "We had to stand in a queue for two hours to get tickets.", level: "B1" },
  { term: "redundant", meaning: "gereksiz, işten çıkarılmış", hint: "not or no longer needed or useful", example: "Eighty employees were made redundant last month.", level: "C1" },
  { term: "retain", meaning: "muhafaza etmek, korumak", hint: "to continue to have something; keep possession of", example: "The soil here doesn't retain water very well.", level: "C1" },
  { term: "scarce", meaning: "kıt, nadir", hint: "especially of food, money, or some other resource insufficient for the demand", example: "Food and clean water were becoming scarce.", level: "C1" },
  { term: "severe", meaning: "ciddi, şiddetli", hint: "of something bad or undesirable very great; intense", example: "The building suffered severe damage in the earthquake.", level: "B2" },
  { term: "tangible", meaning: "somut, elle tutulur", hint: "perceptible by touch", example: "We need tangible evidence if we're going to take legal action.", level: "C1" },
  { term: "thrive", meaning: "gelişmek, serpilmek", hint: "to grow or develop well or vigorously", example: "His business continues to thrive despite the crisis.", level: "C1" },
  { term: "unanimous", meaning: "oybirliğiyle", hint: "held or carried by everyone involved", example: "The jury reached a unanimous verdict.", level: "C2" },
  { term: "underlying", meaning: "altında yatan, temel", hint: "significant as a cause or basis of something but not necessarily manifest", example: "We need to discover the underlying causes of the problem.", level: "C2" },
  { term: "valid", meaning: "geçerli, mantıklı", hint: "having a sound basis in logic or fact", example: "You must have a valid passport to travel abroad.", level: "B2" },
  { term: "versatile", meaning: "çok yönlü", hint: "able to adapt or be adapted to many different functions or activities", example: "He is a very versatile actor who can play any role.", level: "C1" },
  { term: "withdraw", meaning: "geri çekmek, para çekmek", hint: "to remove or take away", example: "I need to withdraw some cash from the ATM.", level: "B2" },
  { term: "widespread", meaning: "yaygın", hint: "found or distributed over a large area or number of people", example: "There was widespread support for the new environmental laws.", level: "B2" },
  { term: "arbitrary", meaning: "keyfi, rastgele", hint: "based on random choice or personal whim", example: "His meal times were entirely arbitrary.", level: "C1" },
  { term: "benevolent", meaning: "iyiliksever, sevecen", hint: "well meaning and kindly", example: "He was a benevolent boss who cared about his employees.", level: "C1" },
  { term: "concise", meaning: "kısa ve öz", hint: "giving a lot of information clearly and in a few words", example: "Please keep your presentation concise.", level: "B2" },
  { term: "depict", meaning: "tasvir etmek, betimlemek", hint: "to show or represent by a drawing, painting, or other art form", example: "The painting depicts a beautiful spring day.", level: "C1" },
  { term: "eccentric", meaning: "tuhaf, alışılmışın dışında", hint: "unconventional and slightly strange", example: "My neighbor is an eccentric old man who talks to his plants.", level: "C1" },
  { term: "feasible", meaning: "mümkün, yapılabilir", hint: "possible to do easily or conveniently", example: "Is it feasible to finish the work by Friday?", level: "B2" },
  { term: "gregarious", meaning: "sosyal, girişken", hint: "fond of company; sociable", example: "Parrots are highly gregarious birds.", level: "C2" },
  { term: "hierarchy", meaning: "hiyerarşi, aşama sırası", hint: "a system or organization in which people or groups are ranked one above the other", example: "The military has a very strict hierarchy.", level: "C1" },
  { term: "imminent", meaning: "eli kulağında, yakın", hint: "about to happen", example: "They were in imminent danger of being swept away.", level: "C2" },
  { term: "juxtapose", meaning: "yan yana koymak, karşılaştırmak", hint: "to place or deal with close together for contrasting effect", example: "Black and white photos were juxtaposed to show the difference.", level: "C2" },
  { term: "knack", meaning: "beceri, yetenek", hint: "an acquired or natural skill at performing a task", example: "She has a knack for remembering faces.", level: "C1" },
  { term: "lenient", meaning: "hoşgörülü, yumuşak", hint: "more merciful or tolerant than expected", example: "The judge was lenient because of his age.", level: "C1" },
  { term: "meticulous", meaning: "titiz, kılı kırk yaran", hint: "showing great attention to detail", example: "He is very meticulous about his personal hygiene.", level: "C1" },
  { term: "nostalgic", meaning: "özlemli, nostaljik", hint: "feeling, evoking, or characterized by nostalgia", example: "Hearing that old song made me feel nostalgic.", level: "B2" },
  { term: "oblivious", meaning: "habersiz, kayıtsız", hint: "not aware of or not concerned about what is happening around one", example: "She was completely oblivious to his presence.", level: "C1" },
  { term: "plausible", meaning: "makul, akla yatkın", hint: "seeming reasonable or probable", example: "That is a plausible explanation for the mistake.", level: "C1" },
  { term: "quirk", meaning: "tuhaflık, garip huy", hint: "a peculiar behavioral habit", example: "Everyone has their own little quirks.", level: "C1" },
  { term: "scrutinize", meaning: "dikkatle incelemek", hint: "to examine or inspect closely and thoroughly", example: "The lawyer will scrutinize the document before signing it.", level: "C2" },
  { term: "tedious", meaning: "sıkıcı, bıktırıcı", hint: "too long, slow, or dull; tiresome", example: "Entering all this data is a tedious task.", level: "C1" },
  { term: "ubiquitous", meaning: "her yerde bulunan", hint: "present, appearing, or found everywhere", example: "Smartphones have become ubiquitous in modern society.", level: "C2" },
  { term: "vulnerable", meaning: "savunmasız, kırılgan", hint: "susceptible to physical or emotional attack or harm", example: "Old people are particularly vulnerable to the flu.", level: "B2" },
  { term: "wane", meaning: "azalmak, zayıflamak", hint: "to decrease in vigor, power, or extent; become weaker", example: "By the late 1970s, the band's popularity had begun to wane.", level: "C2" },
  { term: "xenophobia", meaning: "yabancı düşmanlığı", hint: "dislike of or prejudice against people from other countries", example: "The economic crisis fueled racism and xenophobia.", level: "C2" },
  { term: "yearn", meaning: "özlem duymak, can atmak", hint: "to have an intense feeling of longing for something", example: "I yearn for the days when life was simpler.", level: "C1" },
  { term: "zenith", meaning: "zirve, doruk noktası", hint: "the time at which something is most powerful or successful", example: "His career reached its zenith in the 1990s.", level: "C2" },
  { term: "ample", meaning: "bol, yeterinden fazla", hint: "enough or more than enough; plentiful", example: "There is ample parking space at the new mall.", level: "B2" },
  { term: "bypass", meaning: "etrafından dolanmak, es geçmek", hint: "to go past or around", example: "They built a new road to bypass the town center.", level: "C1" },
  { term: "cynical", meaning: "alaycı, kötümser", hint: "believing that people are motivated by self-interest", example: "He has a very cynical attitude toward politics.", level: "C1" },
  { term: "diminish", meaning: "azalmak, eksiltmek", hint: "to make or become less", example: "The pain will diminish after a few days.", level: "B2" },
  { term: "elicit", meaning: "ortaya çıkarmak, temin etmek", hint: "to evoke or draw out a response", example: "The comedian tried to elicit a laugh from the audience.", level: "C2" },
  { term: "foster", meaning: "teşvik etmek, büyütmek", hint: "to encourage or promote the development of", example: "The teacher tries to foster a love of reading in her students.", level: "C1" },
  { term: "gauge", meaning: "ölçmek, tahmin etmek", hint: "to estimate or determine the magnitude, amount, or volume of", example: "It is difficult to gauge how long the project will take.", level: "C1" },
  { term: "hypothesis", meaning: "varsayım, hipotez", hint: "a supposition or proposed explanation made on the basis of limited evidence", example: "We designed an experiment to test this hypothesis.", level: "B2" },
  { term: "ignite", meaning: "tutuşturmak, ateşlemek", hint: "to catch fire or cause to catch fire", example: "A tiny spark is enough to ignite the dry grass.", level: "C1" },
  { term: "jolt", meaning: "sarsmak, şok etmek", hint: "to push or shake abruptly and roughly", example: "The sudden stop gave us a terrible jolt.", level: "C1" },
  { term: "kudos", meaning: "övme, takdir", hint: "praise and honor received for an achievement", example: "Kudos to everyone who helped organize the event.", level: "C2" },
  { term: "linger", meaning: "oyalanmak, gitmek bilmemek", hint: "to stay in a place longer than necessary", example: "The smell of her perfume lingered in the empty room.", level: "C1" },
  { term: "mundane", meaning: "sıradan, tekdüze", hint: "lacking interest or excitement; dull", example: "I have to do mundane chores like washing the dishes.", level: "C1" },
  { term: "nurture", meaning: "büyütmek, beslemek", hint: "to care for and encourage the growth or development of", example: "Parents want to nurture their children's talents.", level: "C1" },
  { term: "omit", meaning: "atlamak, dahil etmemek", hint: "to leave out or exclude", example: "Please omit my name from the guest list.", level: "B2" },
  { term: "peak", meaning: "zirve", hint: "the highest, strongest, or best point, value, or level of skill", example: "Traffic reaches its peak between 8 and 9 in the morning.", level: "B1" },
  { term: "query", meaning: "sorgu, soru", hint: "a question, especially one addressed to an official or organization", example: "If you have a query about your bill, please contact us.", level: "B2" },
  { term: "render", meaning: "hale getirmek, sunmak", hint: "to provide or give a service, help, etc.", example: "The virus rendered the computer completely useless.", level: "C1" },
  { term: "savvy", meaning: "anlayışlı, pratik zekalı", hint: "shrewdness and practical knowledge", example: "She is very tech-savvy and fixes our computers.", level: "C1" },
  { term: "tact", meaning: "incelik, patavatsız olmama", hint: "adroitness and sensitivity in dealing with others or with difficult issues", example: "The situation requires a lot of tact and diplomacy.", level: "C1" },
  { term: "utmost", meaning: "en son, azami", hint: "most extreme; greatest", example: "This matter is of the utmost importance.", level: "C1" },
  { term: "vein", meaning: "damar, tarz", hint: "any of the tubes forming part of the blood circulation system", example: "The nurse struggled to find a vein in my arm.", level: "B2" },
  { term: "weary", meaning: "yorgun, bitkin", hint: "feeling or showing tiredness", example: "He gave a long, weary sigh.", level: "C1" },
  { term: "yacht", meaning: "yat", hint: "a medium-sized sailboat equipped for cruising or racing", example: "They spent the summer sailing their yacht in the Mediterranean.", level: "B1" },
  { term: "zeal", meaning: "şevk, heves", hint: "great energy or enthusiasm in pursuit of a cause or an objective", example: "His zeal for the project was contagious.", level: "C2" },
  { term: "aesthetic", meaning: "estetik, sanatsal", hint: "concerned with beauty or the appreciation of beauty", example: "The new building has little aesthetic appeal.", level: "C1" },
  { term: "boisterous", meaning: "gürültücü, taşkın", hint: "noisy, energetic, and cheerful; rowdy", example: "A group of boisterous teenagers entered the cafe.", level: "C2" },
  { term: "candid", meaning: "içten, samimi", hint: "truthful and straightforward; frank", example: "To be candid, I think you made a terrible mistake.", level: "C1" },
  { term: "deduce", meaning: "sonuç çıkarmak", hint: "to arrive at a fact or a conclusion by reasoning", example: "We can deduce a lot from what people choose to buy.", level: "C1" },
  { term: "emulate", meaning: "taklit etmek, benzemeye çalışmak", hint: "to match or surpass a person or achievement, typically by imitation", example: "Sons often try to emulate their fathers.", level: "C2" },
  { term: "flaw", meaning: "kusur, hata", hint: "a mark, fault, or other imperfection", example: "The only flaw in his plan was that he had no money.", level: "B2" },
  { term: "genre", meaning: "tür, çeşit", hint: "a category of artistic composition", example: "Science fiction is my favorite literary genre.", level: "B2" },
  { term: "hamper", meaning: "engellemek, köstek olmak", hint: "to hinder or impede the movement or progress of", example: "Heavy rain hampered the rescue operation.", level: "C1" },
  { term: "ideology", meaning: "ideoloji, düşünce yapısı", hint: "a system of ideas and ideals", example: "The party's ideology is based on socialism.", level: "C1" },
  { term: "jargon", meaning: "jargon, mesleki dil", hint: "special words or expressions that are used by a particular profession", example: "The manual is full of technical jargon.", level: "C1" },
  { term: "kindred", meaning: "benzer, akraba", hint: "similar in kind; related", example: "We recognized each other as kindred spirits.", level: "C2" },
  { term: "lament", meaning: "ağıt yakmak, sızlanmak", hint: "a passionate expression of grief or sorrow", example: "He lamented the loss of his old friend.", level: "C2" },
  { term: "morbid", meaning: "marazi, hastalıklı", hint: "characterized by or appealing to an abnormal and unhealthy interest in disturbing and unpleasant subjects", example: "He has a morbid fascination with death.", level: "C2" },
  { term: "novice", meaning: "çaylak, acemi", hint: "a person new to or inexperienced in a field or situation", example: "I am a complete novice when it comes to playing chess.", level: "B2" },
  { term: "orthodox", meaning: "geleneksel, kabul görmüş", hint: "conforming to what is generally or traditionally accepted as right or true", example: "He holds very orthodox views on education.", level: "C1" },
  { term: "paradigm", meaning: "paradigma, model", hint: "a typical example or pattern of something", example: "The war caused a shift in the political paradigm.", level: "C2" },
  { term: "quaint", meaning: "şirin, antika", hint: "attractively unusual or old-fashioned", example: "We stayed in a quaint little village in the mountains.", level: "C1" },
  { term: "ramification", meaning: "sonuç, dallanıp budaklanma", hint: "a consequence of an action or event, especially when complex or unwelcome", example: "Have you considered all the ramifications of your decision?", level: "C2" },
  { term: "sanctuary", meaning: "sığınak, tapınak", hint: "a place of refuge or safety", example: "The park is a wildlife sanctuary.", level: "C1" },
  { term: "tacit", meaning: "üstü kapalı, zımni", hint: "understood or implied without being stated", example: "Your silence may be taken to mean tacit agreement.", level: "C2" },
  { term: "unify", meaning: "birleştirmek", hint: "to make or become united, uniform, or whole", example: "The new leader aims to unify the country.", level: "C1" },
  { term: "viable", meaning: "geçerli, yaşayabilir", hint: "capable of working successfully; feasible", example: "Is this a financially viable option?", level: "C1" },
  { term: "withhold", meaning: "vermemek, alıkoymak", hint: "to refuse to give something that is due to or is desired by another", example: "The company decided to withhold his final paycheck.", level: "C1" },
  { term: "abandon", meaning: "terk etmek, vazgeçmek", hint: "to leave completely and finally", example: "The captain gave the order to abandon ship.", level: "B2" },
  { term: "beneficial", "meaning": "faydalı, yararlı", hint: "favorable or advantageous", example: "Eating vegetables is highly beneficial to your health.", level: "B2" },
  { term: "chaos", meaning: "kaos, karmaşa", hint: "complete disorder and confusion", example: "The power outage caused absolute chaos in the city.", level: "C1" },
  { term: "diagnose", meaning: "teşhis koymak", hint: "to identify the nature of an illness", example: "The doctor was able to diagnose the problem quickly.", level: "B2" },
  { term: "eligible", meaning: "uygun, nitelikli", hint: "having the right to do or obtain something", example: "Only citizens are eligible to vote.", level: "C1" },
  { term: "fascinating", meaning: "büyüleyici, etkileyici", hint: "extremely interesting", example: "I found the documentary about space fascinating.", level: "B1" },
  { term: "glimpse", meaning: "anlık bakış, göz atma", hint: "a momentary or partial view", example: "I only caught a glimpse of the thief's face.", level: "C1" },
  { term: "heritage", meaning: "miras, kalıt", hint: "property that is or may be inherited; tradition", example: "The building is part of our national heritage.", level: "B2" },
  { term: "immune", meaning: "bağışık, etkilenmez", hint: "resistant to a particular infection or toxin", example: "Some people are naturally immune to the virus.", level: "C1" },
  { term: "jeopardy", meaning: "tehlike, risk", hint: "danger of loss, harm, or failure", example: "His foolish actions put the whole mission in jeopardy.", level: "C2" },
  { term: "kidnap", meaning: "kaçırmak (insan)", hint: "to take someone away illegally by force", example: "The terrorists threatened to kidnap the ambassador.", level: "B2" },
  { term: "literacy", meaning: "okuryazarlık", hint: "the ability to read and write", example: "The government launched a campaign to promote adult literacy.", level: "C1" },
  { term: "malicious", meaning: "kötü niyetli, hain", hint: "intending or intended to do harm", example: "The software was designed with malicious intent.", level: "C1" },
  { term: "navigate", meaning: "yönünü bulmak, gezinmek", hint: "to direct the way that a ship, aircraft, or person will travel", example: "We used a map to navigate through the forest.", level: "B2" },
  { term: "obstacle", meaning: "engel, mani", hint: "a thing that blocks one's way or prevents or hinders progress", example: "Lack of money was the biggest obstacle to our plan.", level: "B2" },
  { term: "plague", meaning: "veba, salgın hastalık, rahatsız etmek", hint: "a contagious bacterial disease; to cause continual trouble", example: "Financial problems continued to plague the company.", level: "C1" },
  { term: "quantify", meaning: "nicelendirmek, miktarını belirlemek", hint: "to express or measure the quantity of", example: "It is difficult to quantify the exact impact of the policy.", level: "C1" },
  { term: "radical", meaning: "köklü, radikal", hint: "relating to or affecting the fundamental nature of something", example: "We need to make radical changes to the system.", level: "C1" },
  { term: "sequence", meaning: "sıra, dizi", hint: "a particular order in which related events follow each other", example: "The tasks must be performed in a specific sequence.", level: "B2" },
  { term: "trigger", meaning: "tetiklemek, başlatmak", hint: "to cause an event or situation to happen or exist", example: "Certain foods can trigger a severe allergic reaction.", level: "B2" },
  { term: "utilize", meaning: "kullanmak, yararlanmak", hint: "to make practical and effective use of", example: "We must try to utilize our resources more efficiently.", level: "C1" },
  { term: "vast", meaning: "çok geniş, muazzam", hint: "of very great extent or quantity; immense", example: "The universe is a vast and mysterious place.", level: "B2" },
  { term: "warrant", meaning: "garanti etmek, haklı kılmak", hint: "to justify or necessitate a certain course of action", example: "The situation is serious enough to warrant an investigation.", level: "C2" },
  { term: "ambitious", meaning: "hırslı, iddialı", hint: "having or showing a strong desire and determination to succeed", example: "He is a very ambitious young lawyer.", level: "B2" },
  { term: "bias", meaning: "önyargı", hint: "prejudice in favor of or against one thing", example: "The news report had a clear political bias.", level: "C1" },
  { term: "commodity", meaning: "ticari mal, eşya", hint: "a raw material or primary agricultural product that can be bought and sold", example: "Oil is the country's most valuable commodity.", level: "C1" },
  { term: "deviate", meaning: "sapmak, yön değiştirmek", hint: "to depart from an established course", example: "We must not deviate from our original plan.", level: "C2" },
  { term: "eloquent", meaning: "güzel konuşan, etkili", hint: "fluent or persuasive in speaking or writing", example: "She gave an eloquent speech at the ceremony.", level: "C1" },
  { term: "fluctuation", meaning: "dalgalanma, inip çıkma", hint: "an irregular rising and falling in number or amount", example: "There have been constant fluctuations in the stock market.", level: "C1" },
  { term: "grudge", meaning: "kin, hınç", hint: "a persistent feeling of ill will or resentment", example: "I don't hold a grudge against him for what he did.", level: "C1" },
  { term: "hostage", meaning: "rehin, tutsak", hint: "a person seized or held as security for the fulfillment of a condition", example: "The bank robbers took three people hostage.", level: "B2" },
  { term: "intervene", meaning: "araya girmek, müdahale etmek", hint: "to come between so as to prevent or alter a result", example: "The police had to intervene to stop the fight.", level: "C1" },
  { term: "lucrative", meaning: "karlı, kazançlı", hint: "producing a great deal of profit", example: "She has a lucrative business selling jewelry online.", level: "C1" },
  { term: "moderate", meaning: "ılımlı, orta düzey", hint: "average in amount, intensity, quality, or degree", example: "The doctor advised him to do moderate exercise daily.", level: "B2" },
  { term: "narrative", meaning: "anlatı, hikaye", hint: "a spoken or written account of connected events; a story", example: "The novel is a gripping narrative of survival.", level: "C1" },
  { term: "oblige", meaning: "zorunlu kılmak, minnettar bırakmak", hint: "to make someone legally or morally bound to do something", example: "The law obliges employers to provide a safe workplace.", level: "C1" },
  { term: "prominent", meaning: "öne çıkan, tanınmış", hint: "important; famous", example: "He is a prominent member of the local community.", level: "C1" },
  { term: "revenue", meaning: "gelir, hasılat", hint: "income, especially when of a company or organization", example: "The company's revenue increased by 20% last year.", level: "C1" },
  { term: "subsequent", meaning: "sonraki, ardışık", hint: "coming after something in time; following", example: "The theory was proved wrong in subsequent studies.", level: "B2" },
  { term: "tremendous", meaning: "muazzam, devasa", hint: "very great in amount, scale, or intensity", example: "We have a tremendous amount of work to do.", level: "B2" },
  { term: "undermine", meaning: "baltalamak, zayıflatmak", hint: "to lessen the effectiveness, power, or ability of", example: "This crisis will undermine the government's authority.", level: "C2" },
  { term: "volatile", meaning: "değişken, istikrarsız", hint: "liable to change rapidly and unpredictably", example: "The political situation in the region is highly volatile.", level: "C2" },
  { term: "withdraw", meaning: "geri çekmek, para çekmek", hint: "to remove or take away", example: "She decided to withdraw her application.", level: "B2" },
  { term: "yield", meaning: "ürün vermek, teslim olmak", hint: "to produce or provide; to give way to arguments or pressure", example: "The experiment yielded some surprising results.", level: "C1" },
  { term: "abrupt", meaning: "ani, beklenmedik", hint: "sudden and unexpected", example: "The car came to an abrupt halt.", level: "C1" },
  { term: "chronic", meaning: "kronik, sürekli", hint: "persisting for a long time or constantly recurring", example: "He suffers from chronic back pain.", level: "B2" },
  { term: "dismantle", meaning: "sökmek, parçalara ayırmak", hint: "to take a machine or structure to pieces", example: "The mechanic had to dismantle the engine to fix it.", level: "C2" },
  { term: "endorse", meaning: "onaylamak, desteklemek", hint: "to declare one's public approval or support of", example: "The president refused to endorse the new law.", level: "C1" },
  { term: "accumulate", meaning: "biriktirmek, yığmak", hint: "to gather together or acquire an increasing number or quantity of", example: "Dust tends to accumulate under the bed.", level: "B2" },
  { term: "baffle", meaning: "şaşırtmak, aklını karıştırmak", hint: "to totally bewilder or perplex", example: "An unexpected error continued to baffle the developers.", level: "C1" },
  { term: "coincide", meaning: "aynı zamana denk gelmek", hint: "to occur at or during the same time", example: "My days off coincide with yours this week.", level: "C1" },
  { term: "deteriorate", meaning: "kötüleşmek", hint: "to become progressively worse", example: "Her health began to deteriorate rapidly.", level: "C1" },
  { term: "exaggerate", meaning: "abartmak", hint: "to represent something as being larger or better than it really is", example: "He tends to exaggerate his achievements.", level: "B2" },
  { term: "flawless", meaning: "kusursuz", hint: "without any blemishes or imperfections; perfect", example: "She gave a flawless performance on the piano.", level: "C1" },
  { term: "giggle", meaning: "kıkırdamak", hint: "to laugh lightly in a nervous or silly way", example: "The children started to giggle when the clown appeared.", level: "B2" },
  { term: "hypocrisy", meaning: "ikiyüzlülük", hint: "the practice of claiming to have moral standards to which one's own behavior does not conform", example: "He strongly condemned the hypocrisy of the politicians.", level: "C2" },
  { term: "indigenous", meaning: "yerli", hint: "originating or occurring naturally in a particular place", example: "Kangaroos are indigenous to Australia.", level: "C1" },
  { term: "juggle", meaning: "aynı anda idare etmek, hokkabazlık yapmak", hint: "to continuously toss into the air and catch or cope with several activities at once", example: "Working mothers have to juggle their career and family.", level: "C1" },
  { term: "lucid", meaning: "anlaşılır, açık", hint: "expressed clearly; easy to understand", example: "He gave a very lucid explanation of the problem.", level: "C1" },
  { term: "magnify", meaning: "büyütmek, abartmak", hint: "to make something appear larger than it is", example: "The microscope can magnify objects up to 100 times.", level: "C1" },
  { term: "nuance", meaning: "nüans, ince ayrıntı", hint: "a subtle difference in or shade of meaning", example: "He watched her face closely to catch every nuance of expression.", level: "C1" },
  { term: "outrage", meaning: "öfke, infial", hint: "an extremely strong reaction of anger or shock", example: "The scandal caused public outrage.", level: "C1" },
  { term: "pioneer", meaning: "öncü", hint: "a person who is among the first to explore or settle a new country or area", example: "She was a pioneer in the field of artificial intelligence.", level: "B2" },
  { term: "quarantine", meaning: "karantina", hint: "a state, period, or place of isolation for people or animals that might be sick", example: "The infected animals were placed in strict quarantine.", level: "B2" },
  { term: "relieve", meaning: "hafifletmek, rahatlatmak", hint: "to cause pain, distress, or difficulty to become less severe", example: "These pills should help relieve the pain.", level: "B1" },
  { term: "strive", meaning: "çabalamak, uğraşmak", hint: "to make great efforts to achieve or obtain something", example: "We must strive to improve our services constantly.", level: "C1" },
  { term: "trivial", meaning: "önemsiz, ufak", hint: "of little value or importance", example: "I don't want to waste time on trivial details.", level: "B2" },
  { term: "upheaval", meaning: "büyük kargaşa, çalkantı", hint: "a violent or sudden change or disruption to something", example: "The political upheaval led to a change in government.", level: "C2" },
  { term: "vibrant", meaning: "canlı, hareketli", hint: "full of energy and enthusiasm", example: "Istanbul is known for its vibrant nightlife.", level: "B2" },
  { term: "wholesome", meaning: "sağlıklı, yararlı", hint: "conducive to or suggestive of good health and physical well-being", example: "They enjoy a simple, wholesome diet.", level: "C1" },
  { term: "betray", meaning: "ihanet etmek", hint: "to be disloyal to", example: "He would never betray his best friend's trust.", level: "B2" },
  { term: "conceal", meaning: "gizlemek, saklamak", hint: "to keep from sight; hide", example: "She tried to conceal her nervousness with a smile.", level: "C1" },
  { term: "disrupt", meaning: "aksatmak, bölmek", hint: "to interrupt an event, activity, or process by causing a disturbance", example: "Protesters tried to disrupt the meeting.", level: "C1" },
  { term: "evade", meaning: "kaçınmak, atlatmak", hint: "to escape or avoid, especially by cleverness or trickery", example: "He managed to evade the police for three weeks.", level: "C1" },
  { term: "fatal", meaning: "ölümcül", hint: "causing death", example: "He was involved in a fatal car crash.", level: "B2" },
  { term: "gratitude", meaning: "minnettarlık", hint: "the quality of being thankful", example: "I would like to express my deep gratitude for your support.", level: "B2" },
  { term: "hectic", meaning: "telaşlı, çok yoğun", hint: "full of incessant or frantic activity", example: "I had a very hectic day at the office.", level: "B2" },
  { term: "imply", meaning: "ima etmek", hint: "to strongly suggest the truth or existence of something not expressly stated", example: "Are you trying to imply that I am wrong?", level: "B2" },
  { term: "lethal", meaning: "öldürücü, ölümcül", hint: "sufficient to cause death", example: "They injected him with a lethal dose of poison.", level: "C1" },
  { term: "mingle", meaning: "karışmak, kaynaşmak", hint: "to mix or cause to mix together; move freely around a place", example: "The host went around the room to mingle with the guests.", level: "C1" },
  { term: "notion", meaning: "kavram, düşünce", hint: "a conception of or belief about something", example: "He has this strange notion that everyone is against him.", level: "B2" },
  { term: "prohibit", meaning: "yasaklamak", hint: "to formally forbid something by law, rule, or other authority", example: "The rules prohibit students from using phones during exams.", level: "B2" },
  { term: "relentless", meaning: "acımasız, durmak bilmeyen", hint: "oppressively constant; incessant", example: "The relentless heat made everyone feel exhausted.", level: "C1" },
  { term: "shatter", meaning: "paramparça etmek", hint: "to break suddenly and violently into pieces", example: "The explosion caused the windows to shatter.", level: "B2" },
  { term: "unprecedented", meaning: "görülmemiş, eşi benzeri olmayan", hint: "never done or known before", example: "The government took unprecedented steps to control the crisis.", level: "C1" },
  { term: "vow", meaning: "yemin etmek", hint: "a solemn promise", example: "They exchanged vows in front of their families.", level: "C1" },
  { term: "witty", meaning: "esprili, zekice", hint: "showing or characterized by quick and inventive verbal humor", example: "He is known for his witty remarks.", level: "B2" },
  { term: "zest", meaning: "istek, lezzet", hint: "great enthusiasm and energy", example: "She has a real zest for life.", level: "C2" },
  { term: "ambiguity", meaning: "belirsizlik", hint: "inexactness of meaning in language", example: "We need to clear up the ambiguity in the contract.", level: "C1" },
  { term: "brisk", meaning: "canlı, hareketli, sert", hint: "active, fast, and energetic", example: "We took a brisk walk along the beach.", level: "C1" },
  { term: "consecutive", meaning: "ardışık, peş peşe", hint: "following continuously; in unbroken or logical sequence", example: "It rained for five consecutive days.", level: "C1" },
  { term: "deprive", meaning: "mahrum bırakmak", hint: "to deny the possession or use of something", example: "You cannot deprive a child of a proper education.", level: "C1" },
  { term: "abolish", meaning: "yürürlükten kaldırmak, son vermek", hint: "to formally put an end to a system, practice, or institution", example: "The government decided to abolish the tax completely.", level: "C1" },
  { term: "absorb", meaning: "emmek, içine çekmek, kavramak", hint: "to take in or soak up", example: "Plants absorb carbon dioxide from the air.", level: "B2" },
  { term: "absurd", meaning: "saçma, mantıksız", hint: "wildly unreasonable, illogical, or inappropriate", example: "It is absurd to spend so much on a single pair of shoes.", level: "B2" },
  { term: "accessible", meaning: "ulaşılabilir, erişilebilir", hint: "able to be reached or entered", example: "The building has been made accessible to wheelchairs.", level: "B2" },
  { term: "accommodate", meaning: "barındırmak, yer sağlamak", hint: "to provide lodging or sufficient space for", example: "The hotel can accommodate up to 500 guests.", level: "B2" },
  { term: "accomplish", meaning: "başarmak, sonuçlandırmak", hint: "to achieve or complete successfully", example: "We can accomplish a lot if we work together.", level: "B1" },
  { term: "accountable", meaning: "sorumlu, hesap verebilir", hint: "required or expected to justify actions or decisions", example: "Politicians should be accountable to the public.", level: "C1" },
  { term: "accuracy", meaning: "doğruluk, kesinlik", hint: "the state of being correct or precise", example: "We have to check the accuracy of these figures.", level: "B2" },
  { term: "accusation", meaning: "suçlama", hint: "a charge or claim that someone has done something illegal or wrong", example: "He denied the accusation of theft.", level: "C1" },
  { term: "acquisition", meaning: "edinim, kazanç", hint: "an asset or object bought or obtained", example: "The museum's latest acquisition is a rare painting.", level: "C1" },
  { term: "activate", meaning: "etkinleştirmek, çalıştırmak", hint: "to make something active or operative", example: "You need a code to activate the software.", level: "B2" },
  { term: "addiction", meaning: "bağımlılık", hint: "the fact or condition of being addicted to a particular substance or activity", example: "He is seeking treatment for his drug addiction.", level: "B2" },
  { term: "adequate", meaning: "yeterli, uygun", hint: "satisfactory or acceptable in quality or quantity", example: "This office is perfectly adequate for my needs.", level: "B2" },
  { term: "adhere", meaning: "bağlı kalmak, yapışmak", hint: "to stick fast to a surface or substance; believe in and follow the practices of", example: "All staff must adhere to the safety rules.", level: "C1" },
  { term: "adjacent", meaning: "bitişik, komşu", hint: "next to or adjoining something else", example: "They work in adjacent buildings.", level: "C1" },
  { term: "administer", meaning: "yönetmek, uygulamak", hint: "to manage and be responsible for the running of a business, organization, etc.", example: "The committee was formed to administer the new fund.", level: "C1" },
  { term: "adolescent", meaning: "ergen", hint: "in the process of developing from a child into an adult", example: "The book is aimed at adolescent readers.", level: "C1" },
  { term: "adverse", meaning: "ters, olumsuz", hint: "preventing success or development; harmful; unfavorable", example: "The drug has some serious adverse side effects.", level: "C1" },
  { term: "affection", meaning: "şefkat, sevgi", hint: "a gentle feeling of fondness or liking", example: "She felt deep affection for her grandparents.", level: "C1" },
  { term: "aggravate", meaning: "kötüleştirmek, şiddetlendirmek", hint: "to make a problem, injury, or offense worse or more serious", example: "Stress can aggravate the symptoms of the illness.", level: "C1" },
  { term: "aggregate", meaning: "toplam, bütün", hint: "formed or calculated by the combination of many separate units or items", example: "The aggregate cost of the project was enormous.", level: "C1" },
  { term: "agitation", meaning: "huzursuzluk, çalkantı", hint: "a state of anxiety or nervous excitement", example: "He paced the room in obvious agitation.", level: "C1" },
  { term: "allege", meaning: "iddia etmek, ileri sürmek", hint: "to claim or assert that someone has done something illegal or wrong, typically without proof", example: "The police allege that he was driving too fast.", level: "C1" },
  { term: "alleviate", meaning: "hafifletmek, dindirmek", hint: "to make suffering, deficiency, or a problem less severe", example: "The doctor gave her an injection to alleviate the pain.", level: "C1" },
  { term: "alliance", meaning: "ittifak, birlik", hint: "a union or association formed for mutual benefit", example: "The two countries formed a military alliance.", level: "C1" },
  { term: "allot", meaning: "paylaştırmak, tahsis etmek", hint: "to give or apportion something to someone as a share or task", example: "They were allotted ten minutes for their presentation.", level: "C1" },
  { term: "amateur", meaning: "amatör", hint: "a person who engages in a pursuit on an unpaid rather than a professional basis", example: "The tournament is open to both amateur and professional players.", level: "B2" },
  { term: "amend", meaning: "değiştirmek, düzeltmek (yasa vb.)", hint: "to make minor changes in a text to make it fairer, more accurate, or more up-to-date", example: "They voted to amend the constitution.", level: "C1" },
  { term: "analogy", meaning: "kıyaslama, benzerlik", hint: "a comparison between two things, typically for the purpose of explanation or clarification", example: "He drew an analogy between the brain and a computer.", level: "C1" },
  { term: "anchor", meaning: "demir atmak, sabitlemek", hint: "to secure firmly in position", example: "Make sure the table is anchored securely to the floor.", level: "C1" },
  { term: "anecdote", meaning: "anekdot, fıkra", hint: "a short amusing or interesting story about a real incident or person", example: "He told a funny anecdote about his dog.", level: "C1" },
  { term: "animate", meaning: "canlandırmak, hayat vermek", hint: "to bring to life", example: "A smile suddenly animated her face.", level: "C1" },
  { term: "anomaly", meaning: "anormallik, kuraldışılık", hint: "something that deviates from what is standard, normal, or expected", example: "There are a number of anomalies in the present system.", level: "C2" },
  { term: "anonymous", meaning: "anonim, isimsiz", hint: "not identified by name; of unknown name", example: "The donor wished to remain anonymous.", level: "C1" },
  { term: "anticipate", meaning: "beklemek, ummak", hint: "to regard as probable; expect or predict", example: "We don't anticipate any major problems.", level: "B2" },
  { term: "appalling", meaning: "korkunç, dehşet verici", hint: "awful; terrible", example: "The conditions in the prison were appalling.", level: "C1" },
  { term: "apparatus", meaning: "cihaz, alet", hint: "the technical equipment or machinery needed for a particular activity or purpose", example: "The divers checked their breathing apparatus.", level: "C1" },
  { term: "appeal", meaning: "cezbetmek, başvuruda bulunmak", hint: "to make a serious or urgent request, typically to the public; to be attractive", example: "The idea of living in the country doesn't appeal to me.", level: "B2" },
  { term: "appetite", meaning: "iştah", hint: "a natural desire to satisfy a bodily need, especially for food", example: "A walk in the fresh air gave me a good appetite.", level: "B2" },
  { term: "applaud", meaning: "alkışlamak, takdir etmek", hint: "to show approval or praise by clapping", example: "The audience stood up to applaud the actors.", level: "C1" },
  { term: "applicable", meaning: "uygulanabilir, geçerli", hint: "relevant or appropriate", example: "These rules are not applicable to part-time workers.", level: "C1" },
  { term: "apprehend", meaning: "tutuklamak, kavramak", hint: "to arrest someone for a crime; to understand or perceive", example: "The police managed to apprehend the suspect.", level: "C2" },
  { term: "arrogant", meaning: "kibirli, küstah", hint: "having or revealing an exaggerated sense of one's own importance or abilities", example: "I found him very arrogant and rude.", level: "B2" },
  { term: "articulate", meaning: "kendini iyi ifade edebilen", hint: "having or showing the ability to speak fluently and coherently", example: "She is a highly articulate and confident speaker.", level: "C1" },
  { term: "artificial", meaning: "yapay, suni", hint: "made or produced by human beings rather than occurring naturally", example: "This product contains no artificial colors or flavors.", level: "B2" },
  { term: "ascertain", meaning: "aslını öğrenmek, tespit etmek", hint: "to find something out for certain; make sure of", example: "The police are trying to ascertain the cause of the fire.", level: "C2" },
  { term: "aspire", meaning: "hedeflemek, çok istemek", hint: "to direct one's hopes or ambitions toward achieving something", example: "Most of his students aspire to a career in business.", level: "C1" },
  { term: "assassinate", meaning: "suikast düzenlemek", hint: "to murder an important person in a surprise attack for political or religious reasons", example: "A plot to assassinate the president was uncovered.", level: "C1" },
  { term: "assemble", meaning: "toplamak, monte etmek", hint: "to gather together in one place for a common purpose; to fit together the separate component parts of a machine", example: "It took hours to assemble the new furniture.", level: "B2" },
  { term: "assert", meaning: "iddia etmek, kesin bir dille belirtmek", hint: "to state a fact or belief confidently and forcefully", example: "He continued to assert his innocence despite the evidence.", level: "C1" },
  { term: "astounding", meaning: "şaşırtıcı, hayret verici", hint: "surprisingly impressive or notable", example: "The summit offers an astounding view of the valley.", level: "C1" },
  { term: "bear", meaning: "dayanmak, katlanmak", hint: "to endure an ordeal or difficulty", example: "She couldn't bear the thought of losing him.", level: "B2" },
  { term: "brilliant", meaning: "parlak, zekice", hint: "exceptionally clever or talented", example: "That is a brilliant idea for the new marketing campaign.", level: "B1" },
  { term: "calamity", meaning: "felaket, afet", hint: "an event causing great and often sudden damage or distress", example: "The earthquake was the worst calamity in the country's history.", level: "C2" },
  { term: "capability", meaning: "kabiliyet, yetenek", hint: "the power or ability to do something", example: "The new system has the capability to process data much faster.", level: "B2" },
  { term: "collaborate", meaning: "işbirliği yapmak", hint: "to work jointly on an activity or project", example: "The two companies decided to collaborate on a new smartphone.", level: "C1" },
  { term: "collapse", meaning: "çökmek, yıkılmak", hint: "to fall down or give way suddenly", example: "The bridge is in danger of collapse.", level: "B2" },
  { term: "commence", meaning: "başlamak", hint: "to begin; start", example: "The construction of the new school will commence next month.", level: "C1" },
  { term: "compatible", meaning: "uyumlu", hint: "able to exist or occur together without conflict", example: "This software is not compatible with older operating systems.", level: "C1" },
  { term: "compensate", meaning: "telafi etmek", hint: "to give someone something, typically money, in recognition of loss or suffering", example: "The company will compensate workers for their extra hours.", level: "C1" },
  { term: "complicate", meaning: "karmaşıklaştırmak", hint: "to make something more difficult or confusing", example: "Changing the rules now will only complicate the situation.", level: "B2" },
  { term: "comply", meaning: "uymak, itaat etmek", hint: "to act in accordance with a wish or command", example: "All businesses must comply with the new safety regulations.", level: "C1" },
  { term: "comprehend", meaning: "anlamak, kavramak", hint: "to grasp mentally; understand", example: "It is difficult to comprehend the scale of the universe.", level: "B2" },
  { term: "conceive", meaning: "hayal etmek, tasarlamak", hint: "to form or devise a plan or idea in the mind", example: "He was unable to conceive of a world without technology.", level: "C1" },
  { term: "conclusive", meaning: "kesin, inandırıcı", hint: "serving to prove a case; decisive or convincing", example: "The fingerprints on the weapon provided conclusive evidence.", level: "C1" },
  { term: "condemn", meaning: "kınamak, ayıplamak", hint: "to express complete disapproval of, typically in public", example: "The government was quick to condemn the terrorist attack.", level: "C1" },
  { term: "condense", meaning: "yoğunlaştırmak, özetlemek", hint: "to make something more concentrated or shorter", example: "Can you condense this ten-page report into a short summary?", level: "C1" },
  { term: "conduct", meaning: "yürütmek, idare etmek", hint: "to organize and carry out", example: "The scientists will conduct a series of experiments.", level: "B2" },
  { term: "confess", meaning: "itiraf etmek", hint: "to admit or state that one has committed a crime or is at fault", example: "He eventually confessed to stealing the money.", level: "B1" },
  { term: "confidential", meaning: "gizli", hint: "intended to be kept secret", example: "These documents contain confidential medical information.", level: "C1" },
  { term: "conserve", meaning: "korumak, muhafaza etmek", hint: "to protect from harm or destruction", example: "We need to conserve water during the drought.", level: "C1" },
  { term: "considerable", meaning: "önemli, hatırı sayılır", hint: "notably large in size, amount, or extent", example: "A considerable amount of time was spent on the project.", level: "B2" },
  { term: "consolation", meaning: "teselli, avuntu", hint: "the comfort received by a person after a loss or disappointment", example: "It was a small consolation, but at least nobody was hurt.", level: "C1" },
  { term: "conspicuous", meaning: "göze çarpan, bariz", hint: "standing out so as to be clearly visible", example: "He showed a conspicuous lack of interest in the topic.", level: "C2" },
  { term: "constant", meaning: "sürekli, sabit", hint: "occurring continuously over a period of time", example: "The machine emits a constant low noise.", level: "B2" },
  { term: "contemplate", meaning: "düşünmek, tasarlamak", hint: "to look thoughtfully for a long time at; think profoundly and at length", example: "She sat on the beach, contemplating the meaning of life.", level: "C1" },
  { term: "contradict", meaning: "çelişmek, yalanlamak", hint: "to deny the truth of a statement by asserting the opposite", example: "The witness accounts contradict each other completely.", level: "C1" },
  { term: "contribute", meaning: "katkıda bulunmak", hint: "to give something in order to help achieve or provide something", example: "Many people contributed money to the charity.", level: "B2" },
  { term: "controversy", meaning: "tartışma, anlaşmazlık", hint: "disagreement, typically when prolonged, public, and heated", example: "The new tax policy caused a lot of controversy.", level: "C1" },
  { term: "convene", meaning: "toplanmak, bir araya gelmek", hint: "to come or bring together for a meeting or activity", example: "The committee will convene tomorrow morning.", level: "C1" },
  { term: "convey", meaning: "iletmek, aktarmak", hint: "to make an idea, impression, or feeling known or understandable to someone", example: "Colors can convey different moods and emotions.", level: "C1" },
  { term: "convict", meaning: "mahkum etmek", hint: "to declare someone to be guilty of a criminal offense by the verdict of a jury or the decision of a judge", example: "There wasn't enough evidence to convict him of the crime.", level: "C1" },
  { term: "cope", meaning: "başa çıkmak", hint: "to deal effectively with something difficult", example: "She found it hard to cope with the stress of her new job.", level: "B2" },
  { term: "cordial", meaning: "içten, samimi", hint: "warm and friendly", example: "They received a very cordial welcome at the embassy.", level: "C1" },
  { term: "corrupt", meaning: "yozlaşmış, rüşvetçi", hint: "having or showing a willingness to act dishonestly in return for money or personal gain", example: "The journalist exposed the corrupt politicians.", level: "C1" },
  { term: "counterpart", meaning: "mevkidaş, karşılık", hint: "a person or thing holding a position or performing a function that corresponds to that of another person or thing", example: "The foreign minister met with his German counterpart.", level: "C1" },
  { term: "courteous", meaning: "kibar, nazik", hint: "polite, respectful, or considerate in manner", example: "The hotel staff were highly professional and courteous.", level: "B2" },
  { term: "crave", meaning: "çok istemek, aşermek", hint: "to feel a powerful desire for something", example: "Many young children crave attention from their parents.", level: "C1" },
  { term: "crawl", meaning: "emeklemek, sürünmek", hint: "to move forward on the hands and knees or by dragging the body close to the ground", example: "The baby has just started to crawl.", level: "B1" },
  { term: "credible", meaning: "inandırıcı, güvenilir", hint: "able to be believed; convincing", example: "We need a credible alternative to nuclear power.", level: "C1" },
  { term: "crumble", meaning: "ufalanmak, parçalanmak", hint: "to break or fall apart into small fragments", example: "The old brick wall was beginning to crumble.", level: "C1" },
  { term: "culminate", meaning: "zirveye ulaşmak, sonuçlanmak", hint: "to reach a climax or point of highest development", example: "The festival will culminate in a massive fireworks display.", level: "C2" },
  { term: "cure", meaning: "tedavi etmek, iyileştirmek", hint: "to relieve a person or animal of the symptoms of a disease or condition", example: "They are working hard to find a cure for the virus.", level: "B1" },
  { term: "curious", meaning: "meraklı", hint: "eager to know or learn something", example: "I was curious to find out what had happened.", level: "B1" },
  { term: "dazzle", meaning: "kamaştırmak, büyülemek", hint: "to blind a person temporarily with bright light; to greatly impress someone", example: "He was dazzled by her beauty and intelligence.", level: "C1" },
  { term: "debris", meaning: "enkaz, döküntü", hint: "scattered pieces of waste or remains", example: "Rescue workers searched through the debris for survivors.", level: "C1" },
  { term: "decay", meaning: "çürümek, bozulmak", hint: "to rot or decompose through the action of bacteria and fungi", example: "Sugar can cause tooth decay if you don't brush regularly.", level: "B2" },
  { term: "decent", meaning: "düzgün, makul", hint: "conforming with generally accepted standards of respectable or moral behavior", example: "Everyone deserves a decent standard of living.", level: "B2" },
  { term: "declare", meaning: "ilan etmek, beyan etmek", hint: "to say something in a solemn and emphatic manner", example: "The government was forced to declare a state of emergency.", level: "B2" },
  { term: "decline", meaning: "reddetmek, düşüşe geçmek", hint: "to politely refuse; to become smaller, fewer, or less", example: "I must decline your generous offer.", level: "B2" },
  { term: "defend", meaning: "savunmak, korumak", hint: "to resist an attack made on someone or something", example: "The army was sent to defend the borders.", level: "B1" },
  { term: "deficiency", meaning: "eksiklik, yetersizlik", hint: "a lack or shortage", example: "A vitamin deficiency can lead to serious health issues.", level: "C1" },
  { term: "deliberate", meaning: "kasıtlı, bilerek", hint: "done consciously and intentionally", example: "It was a deliberate attempt to ruin his career.", level: "B2" },
  { term: "delight", meaning: "sevinç, zevk", hint: "great pleasure", example: "The kids screamed with delight when they saw the puppies.", level: "B1" },
  { term: "demonstrate", meaning: "göstermek, kanıtlamak", hint: "to clearly show the existence or truth of something by giving proof or evidence", example: "The study demonstrates the link between poverty and crime.", level: "B2" },
  { term: "derive", meaning: "türetmek, -den elde etmek", hint: "to obtain something from a specified source", example: "Many words in English derive from Latin.", level: "C1" },
  { term: "descend", meaning: "inmek, alçalmak", hint: "to move or fall downward", example: "The plane began to descend slowly.", level: "B2" },
  { term: "deserve", meaning: "hak etmek, layık olmak", hint: "to do something or show qualities worthy of a reward or punishment", example: "You deserve a long vacation after all this hard work.", level: "B1" },
  { term: "desperate", meaning: "çaresiz, umutsuz", hint: "feeling or showing a hopeless sense that a situation is so bad as to be impossible to deal with", example: "They made a desperate attempt to save the company.", level: "B2" },
  { term: "destination", meaning: "varış noktası, hedef", hint: "the place to which someone or something is going or being sent", example: "We finally reached our destination after a ten-hour drive.", level: "B1" },
  { term: "detach", meaning: "ayırmak, sökmek", hint: "to disconnect or separate", example: "You can detach the keyboard from the screen.", level: "C1" },
  { term: "devise", meaning: "tasarlamak, icat etmek", hint: "to plan or invent a complex procedure, system, or mechanism by careful thought", example: "They need to devise a new strategy to attract younger customers.", level: "C2" },
  { term: "devotion", meaning: "bağlılık, sadakat", hint: "love, loyalty, or enthusiasm for a person, activity, or cause", example: "His devotion to his family is truly admirable.", level: "C1" },
  { term: "dictate", meaning: "dikte etmek, emretmek", hint: "to state or order authoritatively", example: "You cannot dictate how I should live my life.", level: "C1" },
  { term: "differentiate", meaning: "ayırt etmek, farkını görmek", hint: "to recognize or ascertain what makes someone or something different", example: "It's difficult to differentiate between the two species.", level: "C1" },
  { term: "digest", meaning: "sindirmek, özümsemek", hint: "to break down food; to understand or assimilate information", example: "I need some time to digest this new information.", level: "C1" },
  { term: "discard", meaning: "atmak, gözden çıkarmak", hint: "to get rid of someone or something as no longer useful or desirable", example: "You should discard any old or expired medicines.", level: "C1" },
  { term: "disclose", meaning: "açığa vurmak, ifşa etmek", hint: "to make secret or new information known", example: "The company refused to disclose the financial details.", level: "C1" },
  { term: "disguise", meaning: "kılık değiştirmek, gizlemek", hint: "to give a different appearance in order to conceal one's identity", example: "He tried to disguise his voice on the phone.", level: "B2" },
  { term: "disgust", meaning: "iğrenme, tiksinti", hint: "a feeling of revulsion or strong disapproval aroused by something unpleasant or offensive", example: "She looked at the messy room with absolute disgust.", level: "B2" },
  { term: "disperse", meaning: "dağılmak, dağıtmak", hint: "to distribute or spread over a wide area", example: "The police used tear gas to disperse the crowd.", level: "C2" },
  { term: "dispose", meaning: "elden çıkarmak, atmak", hint: "to get rid of by throwing away or giving or selling to someone else", example: "Please dispose of your litter thoughtfully.", level: "C1" },
  { term: "dispute", meaning: "anlaşmazlık, tartışma", hint: "a disagreement, argument, or debate", example: "The two countries are involved in a bitter border dispute.", level: "C1" },
  { term: "disregard", meaning: "göz ardı etmek, önemsememek", hint: "to pay no attention to; ignore", example: "You cannot simply disregard the safety warnings.", level: "C1" },
  { term: "dissolve", meaning: "eritmek, feshetmek", hint: "to become or cause to become incorporated into a liquid so as to form a solution", example: "Dissolve the tablet in a glass of water.", level: "C1" },
  { term: "distinguish", meaning: "ayırt etmek", hint: "to recognize or treat someone or something as different", example: "Sometimes it's hard to distinguish fact from fiction.", level: "B2" },
  { term: "distort", meaning: "çarpıtmak, saptırmak", hint: "to pull or twist out of shape; give a misleading account of", example: "The media often distorts reality to get more views.", level: "C1" },
  { term: "distribute", meaning: "dağıtmak, paylaştırmak", hint: "to give shares of something", example: "The organization will distribute food to the homeless.", level: "B2" },
  { term: "divert", meaning: "yönünü değiştirmek, başka yöne çekmek", hint: "to cause someone or something to change course or turn from one direction to another", example: "Traffic was diverted due to the accident.", level: "C1" },
  { term: "divine", meaning: "ilahi, kutsal", hint: "of, from, or like God or a god", example: "Some ancient rulers claimed to have divine power.", level: "C2" },
  { term: "doctrine", meaning: "öğreti, doktrin", hint: "a belief or set of beliefs held and taught by a church, political party, or other group", example: "The president outlined his new military doctrine.", level: "C2" },
  { term: "dominant", meaning: "baskın, hakim", hint: "most important, powerful, or influential", example: "The company holds a dominant position in the global market.", level: "B2" },
  { term: "donate", meaning: "bağışlamak", hint: "to give for a good cause, for example to a charity", example: "Many people donate blood regularly.", level: "B1" },
  { term: "dread", meaning: "korkmak, ürkmek", hint: "to anticipate with great apprehension or fear", example: "I dread going to the dentist.", level: "C1" },
  { term: "duplicate", meaning: "kopyasını çıkarmak, çoğaltmak", hint: "to make an exact copy of", example: "We need to duplicate these documents for the files.", level: "C1" },
  { term: "duration", meaning: "süre, müddet", hint: "the time during which something continues", example: "You should remain in your seats for the duration of the flight.", level: "B2" },
  { term: "eager", meaning: "hevesli, istekli", hint: "strongly wanting to do or have something", example: "The students were eager to learn more about the topic.", level: "B2" },
  { term: "earnest", meaning: "ağırbaşlı, ciddi", hint: "resulting from or showing sincere and intense conviction", example: "He made an earnest promise to improve his behavior.", level: "C1" },
  { term: "ecosystem", meaning: "ekosistem", hint: "a biological community of interacting organisms and their physical environment", example: "Pollution can completely destroy a fragile ecosystem.", level: "C1" },
  { term: "embrace", meaning: "kucaklamak, benimsemek", hint: "to accept or support a belief, theory, or change willingly and enthusiastically", example: "We should embrace new technologies rather than fear them.", level: "C1" },
  { term: "emission", meaning: "salınım, emisyon", hint: "the production and discharge of something, especially gas or radiation", example: "The government plans to cut carbon emissions by 50 percent.", level: "C1" },
  { term: "emphasis", meaning: "vurgu, önem", hint: "special importance, value, or prominence given to something", example: "The school places a strong emphasis on sports.", level: "B2" },
  { term: "empire", meaning: "imparatorluk", hint: "an extensive group of states or countries under a single supreme authority", example: "The Roman Empire was one of the largest in history.", level: "B2" },
  { term: "enable", meaning: "olanak sağlamak, yetki vermek", hint: "to give someone or something the authority or means to do something", example: "This software will enable you to work more efficiently.", level: "B1" },
  { term: "encounter", meaning: "karşılaşmak, rastlamak", hint: "to unexpectedly experience or be faced with something difficult or hostile", example: "We might encounter some problems during the installation.", level: "B2" },
  { term: "endeavor", meaning: "çabalamak, gayret etmek", hint: "to try hard to do or achieve something", example: "Engineers are endeavoring to locate the source of the problem.", level: "C1" },
  { term: "endure", meaning: "katlanmak, dayanmak", hint: "to suffer something painful or difficult patiently", example: "She had to endure a lot of pain after the surgery.", level: "B2" },
  { term: "engage", meaning: "ilgisini çekmek, meşgul etmek", hint: "to occupy, attract, or involve someone's interest or attention", example: "A good teacher knows how to engage students in learning.", level: "B2" },
  { term: "enormous", meaning: "kocaman, devasa", hint: "very large in size, quantity, or extent", example: "They spent an enormous amount of money on the house.", level: "B1" },
  { term: "ensure", meaning: "garantiye almak, emin olmak", hint: "to make certain that something shall occur or be the case", example: "Please ensure that all doors are locked before leaving.", level: "B2" },
  { term: "enterprise", meaning: "girişim, işletme", hint: "a project or undertaking, typically one that is difficult or requires effort", example: "Starting a new business is a risky enterprise.", level: "B2" },
  
];

module.exports = wordsData;