const wordsData = [
{ term: "abandon", meaning: "terk etmek", hint: "bırakmak", example: "They abandoned the project.", level: "B2" },
{ term: "abate", meaning: "azalmak", hint: "dinmek", example: "The storm finally abated.", level: "B2" },
{ term: "abbreviate", meaning: "kısaltmak", hint: "özetlemek", example: "Please abbreviate your answer.", level: "C1" },
{ term: "abide by", meaning: "uymak", hint: "itaat etmek", example: "Abide by the rules.", level: "B2" },
{ term: "abnormal", meaning: "anormal", hint: "olağan dışı", example: "This is abnormal behavior.", level: "B1" },
{ term: "abolish", meaning: "kaldırmak", hint: "feshetmek", example: "They abolished the law.", level: "C1" },
{ term: "abound", meaning: "bol olmak", hint: "çoğalmak", example: "Fish abound in the lake.", level: "C2" },
{ term: "abrupt", meaning: "ani", hint: "beklenmedik", example: "The meeting came to an abrupt end.", level: "C2" },
{ term: "absence", meaning: "yokluk", hint: "bulunmama", example: "His absence was noticed.", level: "C1" },
{ term: "absurd", meaning: "saçma", hint: "anlamsız", example: "The situation is absurd.", level: "C1" },
{ term: "abuse", meaning: "kötüye kullanmak", hint: "istismar etmek", example: "He was accused of abuse.", level: "C1" },
{ term: "academy", meaning: "akademi", hint: "bilim akademisi", example: "She studied at the academy.", level: "C1" },
{ term: "accelerate", meaning: "hızlandırmak", hint: "arttırmak", example: "The car accelerated quickly.", level: "C1" },
{ term: "according to", meaning: "göre", hint: "itibaren", example: "According to the plan, we start.", level: "A2" },
{ term: "account", meaning: "hesap", hint: "açıklamak", example: "He gave an account of events.", level: "B1" },
{ term: "achieve", meaning: "başarmak", hint: "elde etmek", example: "She achieved her goals.", level: "A2" },
{ term: "acknowledge", meaning: "kabullenmek", hint: "tanımak", example: "He acknowledged his mistake.", level: "B2" },
{ term: "accommodate", meaning: "sağlamak", hint: "yer vermek", example: "The hotel can accommodate 200 guests.", level: "B2" },
{ term: "accomplish", meaning: "başarmak", hint: "bitirmek", example: "She accomplished the task.", level: "B2" },
{ term: "account for", meaning: "açıklamak", hint: "sorumlu olmak", example: "This accounts for the difference.", level: "B2" },
{ term: "acquire", meaning: "edinmek", hint: "kazanmak", example: "He acquired new skills.", level: "B2" },
{ term: "adapt", meaning: "uyum sağlamak", hint: "ayarlamak", example: "He adapted to the change.", level: "B2" },
{ term: "adult", meaning: "yetişkin", hint: "olgun", example: "He is an adult now.", level: "A2" },
{ term: "advertise", meaning: "reklam yapmak", hint: "duyurmak", example: "They advertise on TV.", level: "A2" },
{ term: "advice", meaning: "tavsiye", hint: "öğüt", example: "He gave me good advice.", level: "A1" },
{ term: "advise", meaning: "tavsiye etmek", hint: "öğüt vermek", example: "I advise you to listen.", level: "B1" },
{ term: "affect", meaning: "etkilemek", hint: "tesir etmek", example: "It doesn’t affect me.", level: "A2" },
{ term: "afford", meaning: "parası yetmek", hint: "göze almak", example: "We can’t afford this.", level: "B1" },
{ term: "afraid", meaning: "korkmuş", hint: "tuhaf", example: "I am afraid of heights.", level: "A1" },
{ term: "after", meaning: "sonra", hint: "peşinden", example: "We met after lunch.", level: "A1" },
{ term: "against", meaning: "karşı", hint: "lehine", example: "She voted against it.", level: "A2" },
{ term: "again", meaning: "tekrar", hint: "yeniden", example: "Try again later.", level: "A1" },
{ term: "accountability", meaning: "hesap verebilirlik", hint: "sorumluluk", example: "We demand accountability.", level: "C2" },
{ term: "annual", meaning: "yıllık", hint: "her yıl", example: "The annual event is today.", level: "A2" },
{ term: "apply", meaning: "başvurmak", hint: "uygulamak", example: "Please apply online.", level: "A2" },
{ term: "arrive", meaning: "varmak", hint: "ulaşmak", example: "We arrived yesterday.", level: "A1" },
{ term: "assume", meaning: "varsaymak", hint: "üstlenmek", example: "Don't assume the worst.", level: "B1" },
{ term: "available", meaning: "mevcut", hint: "elde edilebilir", example: "Tickets are available.", level: "A1" },
{ term: "away", meaning: "uzakta", hint: "yoksun", example: "He is away today.", level: "A1" },
{ term: "background", meaning: "arka plan", hint: "geçmiş", example: "He has a scientific background.", level: "B1" },
{ term: "benefit", meaning: "fayda", hint: "yarar", example: "He benefits the company.", level: "B1" },
{ term: "beyond", meaning: "ötesinde", hint: "hariç", example: "It's beyond my control.", level: "B2" },
{ term: "bike", meaning: "bisiklet", hint: "motor", example: "He rode his bike.", level: "A1" },
{ term: "body", meaning: "vücut", hint: "gövde", example: "His body is healthy.", level: "A1" },
{ term: "bond", meaning: "bağ", hint: "payan", example: "They formed a strong bond.", level: "B2" },
{ term: "book", meaning: "kitap", hint: "rezerve etmek", example: "She reads a book.", level: "A1" },
{ term: "border", meaning: "sınır", hint: "kenar", example: "We crossed the border.", level: "B1" },
{ term: "both", meaning: "her iki", hint: "ikisi de", example: "Both answers are correct.", level: "A1" },
{ term: "breakfast", meaning: "kahvaltı", hint: "ilk öğün", example: "They had breakfast.", level: "A1" },
{ term: "bridge", meaning: "köprü", hint: "baraj", example: "He crossed the bridge.", level: "A2" },
{ term: "budget", meaning: "bütçe", hint: "plan", example: "Stick to the budget.", level: "B2" },
{ term: "built", meaning: "inşa edilmiş", hint: "kurulu", example: "The house was built recently.", level: "A2" },
{ term: "business", meaning: "iş", hint: "ticaret", example: "He runs a business.", level: "A1" },
{ term: "busy", meaning: "meşgul", hint: "yoğun", example: "She is busy now.", level: "A1" },
{ term: "but", meaning: "ama", hint: "sadece", example: "I wanted to go, but I couldn't.", level: "A1" },
{ term: "buy", meaning: "satın almak", hint: "almak", example: "I will buy a ticket.", level: "A1" },
{ term: "can", meaning: "yapabilmek", hint: "konserve kutusu", example: "She can swim.", level: "A1" },
{ term: "call", meaning: "aramak", hint: "çağırmak", example: "I will call you tonight.", level: "A1" },
{ term: "camera", meaning: "kamera", hint: "fotoğraf makinesi", example: "He bought a new camera.", level: "A1" },
{ term: "camp", meaning: "kamp", hint: "kamp yapmak", example: "They set up camp.", level: "A2" },
{ term: "campaign", meaning: "kampanya", hint: "operasyon", example: "They launched a campaign.", level: "B1" },
{ term: "campus", meaning: "kampüs", hint: "üniversite yerleşkesi", example: "He attends campus classes.", level: "A2" },
{ term: "cancer", meaning: "kanser", hint: "hastalık", example: "She recovered from cancer.", level: "B2" },
{ term: "candidate", meaning: "aday", hint: "aday kişi", example: "He is a candidate.", level: "B1" },
{ term: "cannot", meaning: "yapamamak", hint: "edilgen", example: "She cannot come.", level: "A1" },
{ term: "cap", meaning: "şapka", hint: "kapak", example: "He wore a cap.", level: "B1" },
{ term: "capable", meaning: "yetenekli", hint: "yapabilir", example: "She is capable of great work.", level: "B2" },
{ term: "capacity", meaning: "kapasite", hint: "yetenek", example: "The stadium has a large capacity.", level: "B2" },
{ term: "capital", meaning: "başkent", hint: "sermaye", example: "Paris is the capital of France.", level: "A1" },
{ term: "car", meaning: "araba", hint: "taşıt", example: "He drives a car.", level: "A1" },
{ term: "card", meaning: "kart", hint: "kredi kartı", example: "Pay by card.", level: "A1" },
{ term: "career", meaning: "kariyer", hint: "meslek", example: "She has a successful career.", level: "A2" },
{ term: "careful", meaning: "dikkatli", hint: "özenli", example: "Be careful!", level: "A2" },
{ term: "carelessly", meaning: "dikkatsizce", hint: "özensizce", example: "He drove carelessly.", level: "B2" },
{ term: "carpet", meaning: "halı", hint: "kilim", example: "The room has a red carpet.", level: "A2" },
{ term: "carry", meaning: "taşımak", hint: "sürdürmek", example: "Carry this box upstairs.", level: "A1" },
{ term: "cartoon", meaning: "karikatür", hint: "çizgi film", example: "Children watch cartoons.", level: "A2" },
{ term: "case", meaning: "durum", hint: "kutusu", example: "This is a special case.", level: "A2" },
{ term: "cash", meaning: "nakit", hint: "para", example: "Pay in cash.", level: "A2" },
{ term: "cast", meaning: "döküm", hint: "çalmak", example: "He cast a stone.", level: "B2" },
{ term: "category", meaning: "kategori", hint: "sınıf", example: "This category includes all items.", level: "B1" },
{ term: "cause", meaning: "sebep olmak", hint: "neden", example: "Smoking causes cancer.", level: "A2" },
{ term: "ceil", meaning: "tavan", hint: "çatı", example: "They will ceil the barn.", level: "B2" },
{ term: "ceiling", meaning: "tavan", hint: "üst sınır", example: "The ceiling is high.", level: "B1" },
{ term: "celebrate", meaning: "kutlamak", hint: "eğlenmek", example: "They celebrated a victory.", level: "A2" },
{ term: "celebration", meaning: "kutlama", hint: "eğlence", example: "A big celebration followed.", level: "B1" },
{ term: "celebrity", meaning: "ünlü kişi", hint: "şöhret", example: "He is a movie celebrity.", level: "A2" },
{ term: "cement", meaning: "çimento", hint: "perçinlemek", example: "They poured cement.", level: "B2" },
{ term: "cent", meaning: "sent", hint: "kurşun", example: "A dime is ten cents.", level: "A1" },
{ term: "center", meaning: "merkez", hint: "ortala", example: "Meet at the city center.", level: "A1" },
{ term: "central", meaning: "merkezi", hint: "ana", example: "Central heating is efficient.", level: "B1" },
{ term: "century", meaning: "yüzyıl", hint: "asır", example: "In the 19th century...", level: "A2" },
{ term: "certain", meaning: "belirli", hint: "kesin", example: "I am certain.", level: "A2" },
{ term: "certainly", meaning: "kesinlikle", hint: "elbette", example: "He certainly will come.", level: "A2" },
{ term: "chain", meaning: "zincir", hint: "dizi", example: "The chain is broken.", level: "B1" },
{ term: "chair", meaning: "sandalye", hint: "oturmak", example: "Sit on the chair.", level: "A1" },
{ term: "chairman", meaning: "başkan", hint: "müdür", example: "He is the chairman.", level: "B2" },
{ term: "challenge", meaning: "meydan okumak", hint: "zorlamak", example: "It is a big challenge.", level: "B1" },
{ term: "champion", meaning: "şampiyon", hint: "savunmak", example: "He became champion.", level: "B1" },
{ term: "chance", meaning: "şans", hint: "olasılık", example: "Take a chance.", level: "A2" },
{ term: "change", meaning: "değiştirmek", hint: "yolculuk", example: "Change lanes carefully.", level: "A1" },
{ term: "channel", meaning: "kanal", hint: "yalak", example: "Switch the channel.", level: "B1" },
{ term: "chapter", meaning: "bölüm", hint: "kısım", example: "Read chapter one.", level: "B1" },
{ term: "charge", meaning: "şarj etmek", hint: "görev", example: "Charge your phone.", level: "B1" },
{ term: "charity", meaning: "hayır kurumu", hint: "yardım", example: "Donate to charity.", level: "A2" },
{ term: "chart", meaning: "çizelge", hint: "harita", example: "Look at this chart.", level: "A1" },
{ term: "chat", meaning: "sohbet etmek", hint: "görüşmek", example: "Let's chat later.", level: "A2" },
{ term: "cheap", meaning: "ucuz", hint: "hesaplı", example: "This phone is cheap.", level: "A1" },
{ term: "cheat", meaning: "hile yapmak", hint: "kandırmak", example: "Don't cheat on tests.", level: "B1" },
{ term: "check", meaning: "kontrol etmek", hint: "önlemek", example: "Please check the email.", level: "A1" },
{ term: "chef", meaning: "aşçı", hint: "şef", example: "The chef is cooking.", level: "A2" },
{ term: "chemical", meaning: "kimyasal", hint: "ilaç", example: "Use protective gear.", level: "B1" },
{ term: "chicken", meaning: "tavuk", hint: "coward", example: "He eats chicken.", level: "A1" },
{ term: "chief", meaning: "başlıca", hint: "sorumlu kişi", example: "He is chief engineer.", level: "B2" },
{ term: "child", meaning: "çocuk", hint: "evlat", example: "He is a good child.", level: "A1" },
{ term: "childhood", meaning: "çocukluk", hint: "gençlik", example: "She had a happy childhood.", level: "B1" },
{ term: "chocolate", meaning: "çikolata", hint: "kakao", example: "She loves chocolate.", level: "A1" },
{ term: "choice", meaning: "seçim", hint: "tercih", example: "Make a choice.", level: "A2" },
{ term: "church", meaning: "kilise", hint: "yol", example: "He went to church.", level: "A2" },
{ term: "circle", meaning: "daire", hint: "çember", example: "Draw a circle.", level: "A2" },
{ term: "circumstance", meaning: "durum", hint: "şart", example: "Under any circumstance.", level: "B2" },
{ term: "cite", meaning: "alıntı yapmak", hint: "örneklemek", example: "She cited the law.", level: "B2" },
{ term: "citizen", meaning: "vatandaş", hint: "sakin", example: "Every citizen has rights.", level: "B2" },
{ term: "city", meaning: "şehir", hint: "kent", example: "They live in the city.", level: "A1" },
{ term: "civil", meaning: "sivil", hint: "uygun", example: "Civil law applies.", level: "B2" },
{ term: "claim", meaning: "iddia etmek", hint: "talep etmek", example: "He claimed the prize.", level: "B1" },
{ term: "class", meaning: "sınıf", hint: "ders", example: "I attend class.", level: "A1" },
{ term: "clean", meaning: "temizlemek", hint: "temiz", example: "Keep it clean.", level: "A1" },
{ term: "clear", meaning: "açık", hint: "belirgin", example: "Make it clear.", level: "A2" },
{ term: "clerk", meaning: "tezgahtar", hint: "katip", example: "The clerk helped me.", level: "A2" },
{ term: "client", meaning: "müşteri", hint: "danışan", example: "The client is waiting.", level: "B1" },
{ term: "climate", meaning: "iklim", hint: "hava", example: "Tropical climate is hot.", level: "A2" },
{ term: "climb", meaning: "tırmanmak", hint: "çıkarılmak", example: "Climb the stairs.", level: "A1" },
{ term: "clock", meaning: "saat", hint: "çar saat", example: "Look at the clock.", level: "A1" },
{ term: "close", meaning: "kapatmak", hint: "yakın", example: "Close the door.", level: "A1" },
{ term: "clothes", meaning: "elbise", hint: "giysi", example: "Put on your clothes.", level: "A1" },
{ term: "cloud", meaning: "bulut", hint: "hava", example: "The cloud is white.", level: "A2" },
{ term: "club", meaning: "kulüp", hint: "sopa", example: "He joined the club.", level: "A1" },
{ term: "clue", meaning: "ipuçu", hint: "iz", example: "Find the clue.", level: "B1" },
{ term: "coach", meaning: "antrenör", hint: "otobüs", example: "She is a coach.", level: "A2" },
{ term: "coal", meaning: "kömür", hint: "element", example: "Coal is combustible.", level: "B1" },
{ term: "coast", meaning: "kıyı", hint: "deniz kenarı", example: "He lives on the coast.", level: "A2" },
{ term: "coat", meaning: "kaban", hint: "sürmek", example: "Wear your coat.", level: "A1" },
{ term: "coin", meaning: "bozuk para", hint: "madeni para", example: "I found a coin.", level: "B1" },
{ term: "code", meaning: "kod", hint: "şifre", example: "Enter the code.", level: "A2" },
{ term: "coffee", meaning: "kahve", hint: "içecek", example: "She drinks coffee.", level: "A1" },
{ term: "coin", meaning: "bozuk para", hint: "madeni para", example: "I found a coin.", level: "B1" },
{ term: "cold", meaning: "soğuk", hint: "nezle", example: "It is cold outside.", level: "A1" },
{ term: "collapse", meaning: "çökmek", hint: "yıkılmak", example: "The building will collapse.", level: "B2" },
{ term: "collect", meaning: "toplamak", hint: "biriktirmek", example: "She collects stamps.", level: "A2" },
{ term: "college", meaning: "kolej", hint: "üniversite", example: "I go to college.", level: "A1" },
{ term: "coloured", meaning: "renkli", hint: "boyamak", example: "The walls are coloured blue.", level: "B1" },
{ term: "column", meaning: "sütun", hint: "kolon", example: "Read the column.", level: "A2" },
{ term: "combination", meaning: "kombinasyon", hint: "birleşim", example: "Try a combination of codes.", level: "B2" },
{ term: "combine", meaning: "birleştirmek", hint: "karışmak", example: "Combine red and blue.", level: "B1" },
{ term: "come", meaning: "gelmek", hint: "yaklaşmak", example: "Come here.", level: "A1" },
{ term: "comedy", meaning: "komedi", hint: "gülünç oyun", example: "They watched a comedy.", level: "A2" },
{ term: "comfort", meaning: "rahatlık", hint: "teskin etmek", example: "Find comfort in music.", level: "B2" },
{ term: "command", meaning: "emretmek", hint: "komuta", example: "Follow the command.", level: "B2" },
{ term: "comment", meaning: "yorum yapmak", hint: "açıklama", example: "Leave a comment.", level: "A2" },
{ term: "commercial", meaning: "ticari", hint: "reklam", example: "He appeared in a commercial.", level: "B1" },
{ term: "commission", meaning: "komisyon", hint: "görevlendirmek", example: "Pay a commission.", level: "B2" },
{ term: "commit", meaning: "işlemek", hint: "adamak", example: "He committed a crime.", level: "B1" },
{ term: "commitment", meaning: "taahhüt", hint: "sorumluluk", example: "She showed commitment.", level: "B2" },
{ term: "committee", meaning: "komite", hint: "kurul", example: "Join the committee.", level: "B2" },
{ term: "common", meaning: "ortak", hint: "sıradan", example: "It's a common issue.", level: "A1" },
{ term: "communicate", meaning: "iletişim kurmak", hint: "bildirmek", example: "We communicate by email.", level: "A2" },
{ term: "communism", meaning: "komünizm", hint: "ideoloji", example: "They studied communism.", level: "C2" },
{ term: "community", meaning: "topluluk", hint: "halk", example: "Volunteer for the community.", level: "A2" },
{ term: "company", meaning: "şirket", hint: "arkadaşlık", example: "He works at the company.", level: "A1" },
{ term: "comparison", meaning: "karşılaştırma", hint: "tezat", example: "Make a comparison.", level: "B1" },
{ term: "compete", meaning: "yarışmak", hint: "rekabet etmek", example: "Athletes compete internationally.", level: "A2" },
{ term: "competition", meaning: "yarışma", hint: "rekabet", example: "The competition is tough.", level: "A2" },
{ term: "competitive", meaning: "rekabetçi", hint: "yarışmacı", example: "They are competitive.", level: "B1" },
{ term: "competitor", meaning: "yarışmacı", hint: "rakip", example: "She is the top competitor.", level: "B1" },
{ term: "complain", meaning: "şikayet etmek", hint: "yakınmak", example: "They complain frequently.", level: "A2" },
{ term: "complaint", meaning: "şikayet", hint: "yasama", example: "File a complaint.", level: "B1" },
{ term: "complete", meaning: "tamamlamak", hint: "eksiksiz", example: "Complete the form.", level: "A1" },
{ term: "complex", meaning: "karmaşık", hint: "bütün", example: "A complex problem.", level: "B1" },
{ term: "complicated", meaning: "karmaşık", hint: "karışık", example: "It's a complicated issue.", level: "B2" },
{ term: "component", meaning: "bileşen", hint: "parça", example: "Missing component.", level: "B2" },
{ term: "conceive", meaning: "tasavvur etmek", hint: "düşünmek", example: "She conceived the plan.", level: "C1" },
{ term: "concentrate", meaning: "yoğunlaşmak", hint: "konsantre olmak", example: "Concentrate on your work.", level: "B1" },
{ term: "concern", meaning: "ilgilenmek", hint: "kaygı", example: "He felt concern.", level: "B2" },
{ term: "concert", meaning: "konser", hint: "anlaşma", example: "Attend the concert.", level: "A1" },
{ term: "conclude", meaning: "sonuçlandırmak", hint: "karar vermek", example: "Conclude the meeting.", level: "B1" },
{ term: "conclusion", meaning: "sonuç", hint: "karar", example: "In conclusion ...", level: "B1" },
{ term: "condition", meaning: "durum", hint: "koşul", example: "Under these conditions...", level: "A2" },
{ term: "conduct", meaning: "davranmak", hint: "yürütmek", example: "Conduct the experiment.", level: "B2" },
{ term: "conference", meaning: "konferans", hint: "toplantı", example: "Attend the conference.", level: "A2" },
{ term: "confidence", meaning: "özgüven", hint: "güven", example: "She has confidence.", level: "B2" },
{ term: "congress", meaning: "kongre", hint: "toplantı", example: "Congress is in session.", level: "B2" },
{ term: "connect", meaning: "bağlamak", hint: "ilişkilendirmek", example: "Connect the wires.", level: "A2" },
{ term: "conscious", meaning: "bilinçli", hint: "uyanık", example: "Be conscious of others.", level: "B2" },
{ term: "consequence", meaning: "sonuç", hint: "netice", example: "Face the consequence.", level: "B1" },
{ term: "consider", meaning: "düşünmek", hint: "değerlendirmek", example: "I consider it a success.", level: "A2" },
{ term: "consideration", meaning: "düşünce", hint: "hesaba katma", example: "Take this into consideration.", level: "B2" },
{ term: "consistent", meaning: "tutarlı", hint: "sürekli", example: "Be consistent.", level: "B2" },
{ term: "constant", meaning: "sürekli", hint: "sabit", example: "Temperatures remain constant.", level: "B2" },
{ term: "construction", meaning: "inşaat", hint: "yapı", example: "Construction is ongoing.", level: "B2" },
{ term: "contain", meaning: "içermek", hint: "tutmak", example: "Containers contain goods.", level: "A2" },
{ term: "continue", meaning: "devam etmek", hint: "sürdürmek", example: "Continue your journey.", level: "A2" },
{ term: "convert", meaning: "dönüştürmek", hint: "değiştirmek", example: "Convert units.", level: "B2" },
{ term: "convince", meaning: "ikna etmek", hint: "inandırmak", example: "Convince him.", level: "B1" },
{ term: "cook", meaning: "pişirmek", hint: "aşçı", example: "She cooks dinner.", level: "A1" },
{ term: "cool", meaning: "serin", hint: "soğutmak", example: "Stay cool.", level: "A1" },
{ term: "copy", meaning: "kopyalamak", hint: "çoğaltmak", example: "Copy the text.", level: "A2" },
{ term: "corn", meaning: "mısır", hint: "tahıl", example: "She bought corn.", level: "B1" },
{ term: "corner", meaning: "köşe", hint: "meydan", example: "Turn the corner.", level: "A2" },
{ term: "corporate", meaning: "kurumsal", hint: "şirketle ilgili", example: "A corporate meeting.", level: "B2" },
{ term: "correct", meaning: "doğru", hint: "düzeltmek", example: "Give the correct answer.", level: "A1" },
{ term: "cost", meaning: "maliyet", hint: "değer", example: "The cost is $10.", level: "A1" },
{ term: "cottage", meaning: "kulübe", hint: "kır evi", example: "Stay in the cottage.", level: "C1" },
{ term: "could", meaning: "yapabilirdi", hint: "can'ın geçmişi", example: "She could help.", level: "A1" },
{ term: "council", meaning: "konsey", hint: "encümen", example: "City council meeting.", level: "B2" },
{ term: "count", meaning: "saymak", hint: "hesaba katmak", example: "Count the votes.", level: "A2" },
{ term: "country", meaning: "ülke", hint: "kırsal", example: "He visited many countries.", level: "A1" },
{ term: "county", meaning: "ilçe", hint: "bölge", example: "This county is large.", level: "B2" },
{ term: "couple", meaning: "çift", hint: "iki", example: "A couple of hours.", level: "A2" },
{ term: "course", meaning: "ders", hint: "yemek", example: "Take the online course.", level: "A1" },
{ term: "court", meaning: "mahalle", hint: "duruşma", example: "She went to court.", level: "B1" },
{ term: "cousin", meaning: "kuzen", hint: "akraba", example: "My cousin lives nearby.", level: "A1" },
{ term: "cover", meaning: "örtmek", hint: "kapatmak", example: "Cover your face.", level: "A2" },
{ term: "cow", meaning: "inek", hint: "kadın", example: "A cow in the field.", level: "A1" },
{ term: "crash", meaning: "çarpışma", hint: "kaza yapmak", example: "They saw a crash.", level: "B2" },
{ term: "cream", meaning: "krema", hint: "krem", example: "Add cream to coffee.", level: "A1" },
{ term: "create", meaning: "yaratmak", hint: "oluşturmak", example: "Create a new file.", level: "A1" },
{ term: "creation", meaning: "yaratım", hint: "tasarım", example: "The creation is art.", level: "B2" },
{ term: "creative", meaning: "yaratıcı", hint: "üretken", example: "She is very creative.", level: "A2" },
{ term: "credit", meaning: "kredi", hint: "takdir", example: "Give credit when due.", level: "A2" },
{ term: "crew", meaning: "ekip", hint: "mürettebat", example: "The ship’s crew.", level: "B2" },
{ term: "crime", meaning: "suç", hint: "kabahat", example: "Crime rates are falling.", level: "A2" },
{ term: "criminal", meaning: "suçlu", hint: "cezaevi", example: "He is a criminal.", level: "A2" },
{ term: "crisis", meaning: "kriz", hint: "buhran", example: "Economic crisis hit.", level: "B2" },
{ term: "criterion", meaning: "ölçüt", hint: "kriter", example: "Meet the criterion.", level: "B2" },
{ term: "critic", meaning: "eleştirmen", hint: "akın etmek", example: "She is a critic.", level: "B2" },
{ term: "critical", meaning: "kritik", hint: "eleştirel", example: "This is critical.", level: "B2" },
{ term: "criticism", meaning: "eleştiri", hint: "hüküm", example: "He faced criticism.", level: "B2" },
{ term: "criticize", meaning: "eleştirmek", hint: "kusur bulmak", example: "Don't criticize him.", level: "B2" },
{ term: "crop", meaning: "ürün", hint: "ekin", example: "Corn is the crop.", level: "B2" },
{ term: "cross", meaning: "karşıya geçmek", hint: "haç", example: "Cross the street.", level: "A2" },
{ term: "crowd", meaning: "kalabalık", hint: "topluluk", example: "A crowd gathered.", level: "A2" },
{ term: "crowded", meaning: "kalabalık", hint: "dolu", example: "The room is crowded.", level: "A2" },
{ term: "crucial", meaning: "kritik", hint: "önemli", example: "A crucial decision.", level: "B2" },
{ term: "cry", meaning: "ağlamak", hint: "çığlık atmak", example: "Don't cry.", level: "A2" },
{ term: "cultural", meaning: "kültürel", hint: "medeniyet", example: "Cultural change.", level: "B1" },
{ term: "culture", meaning: "kültür", hint: "medeniyet", example: "Rich culture.", level: "A1" },
{ term: "cup", meaning: "bardak", hint: "kupa", example: "He drank from the cup.", level: "A1" },
{ term: "curly", meaning: "kıvırcık", hint: "dalgalı", example: "Curly hair.", level: "A2" },
{ term: "currency", meaning: "para birimi", hint: "değer", example: "Euro is currency.", level: "B1" },
{ term: "current", meaning: "mevcut", hint: "akım", example: "The current trend.", level: "B1" },
{ term: "current affairs", meaning: "gündem", hint: "güncel olaylar", example: "They discussed current affairs.", level: "C2" },
{ term: "currently", meaning: "şu anda", hint: "halen", example: "Currently busy.", level: "B1" },
{ term: "customer", meaning: "müşteri", hint: "alıcı", example: "The customer is right.", level: "A2" },
{ term: "cut", meaning: "kesmek", hint: "azalmak", example: "Cut the paper.", level: "A1" },
{ term: "cycle", meaning: "döngü", hint: "bisiklet sürmek", example: "A cycle repeats.", level: "A2" },
{ term: "dad", meaning: "baba", hint: "dede", example: "Call your dad.", level: "A1" },
{ term: "daily", meaning: "günlük", hint: "her gün", example: "He goes to work daily.", level: "A2" },
{ term: "damage", meaning: "zarar", hint: "hasar", example: "Fix the damage.", level: "B1" },
{ term: "dance", meaning: "dans etmek", hint: "dans", example: "They dance every week.", level: "A1" },
{ term: "danger", meaning: "tehlike", hint: "risk", example: "Be aware of danger.", level: "A2" },
{ term: "dangerous", meaning: "tehlikeli", hint: "zararlı", example: "Fire is dangerous.", level: "A1" },
{ term: "dark", meaning: "karanlık", hint: "koyu", example: "It gets dark early.", level: "A1" },
{ term: "data", meaning: "veri", hint: "bilgi", example: "Collect the data.", level: "A2" },
{ term: "date", meaning: "tarih", hint: "randevu", example: "Today's date is May 1st.", level: "A1" },
{ term: "daughter", meaning: "kız evlat", hint: "kadın çocuğu", example: "He has one daughter.", level: "A1" },
{ term: "day", meaning: "gün", hint: "gündüz", example: "Have a nice day.", level: "A1" },
{ term: "dead", meaning: "ölü", hint: "gammaz", example: "He fell dead.", level: "A2" },
{ term: "deal", meaning: "anlaşma yapmak", hint: "dağıtmak", example: "Let's make a deal.", level: "A2" },
{ term: "dear", meaning: "sevgili", hint: "değerli", example: "My dear friend.", level: "A1" },
{ term: "death", meaning: "ölüm", hint: "vefat", example: "The death was sudden.", level: "A2" },
{ term: "debate", meaning: "tartışma", hint: "münazara", example: "They will debate tomorrow.", level: "B2" },
{ term: "debt", meaning: "borç", hint: "icra", example: "Clear your debts.", level: "B2" },
{ term: "decade", meaning: "on yıl", hint: "yıl dönümü", example: "He lived abroad for a decade.", level: "B1" },
{ term: "December", meaning: "Aralık", hint: "yılbaşı", example: "Winter comes in December.", level: "A1" },
{ term: "decide", meaning: "karar vermek", hint: "seçmek", example: "Decide quickly.", level: "A1" },
{ term: "decision", meaning: "karar", hint: "azim", example: "That is my decision.", level: "A2" },
{ term: "declare", meaning: "ilan etmek", hint: "beyan etmek", example: "He declared his love.", level: "B2" },
{ term: "decline", meaning: "azalmak", hint: "reddetmek", example: "Prices decline.", level: "B2" },
{ term: "decorate", meaning: "süslemek", hint: "boyamak", example: "Decorate the room.", level: "B2" },
{ term: "decorative", meaning: "süslü", hint: "adornmayı", example: "Use decorative items.", level: "C1" },
{ term: "decrease", meaning: "azalma", hint: "indirmek", example: "Decrease the volume.", level: "B2" },
{ term: "deep", meaning: "derin", hint: "yoğun", example: "Water is deep.", level: "A2" },
{ term: "defeat", meaning: "yenmek", hint: "bozguna uğratmak", example: "Defeat the champion.", level: "B2" },
{ term: "defend", meaning: "savunmak", hint: "muhafaza etmek", example: "Defend your team.", level: "B2" },
{ term: "deficit", meaning: "açık", hint: "eksi", example: "Budget deficit.", level: "C2" },
{ term: "define", meaning: "tanımlamak", hint: "sınırlandırmak", example: "Define the terms.", level: "B1" },
{ term: "definite", meaning: "belirli", hint: "kesin", example: "That's a definite answer.", level: "B1" },
{ term: "definitely", meaning: "kesinlikle", hint: "elbette", example: "Definitely true.", level: "A2" },
{ term: "definition", meaning: "tanım", hint: "anlam", example: "Give a clear definition.", level: "B1" },
{ term: "degree", meaning: "derece", hint: "ünvan", example: "She has a degree in law.", level: "A2" },
{ term: "delay", meaning: "gecikme", hint: "oyalamak", example: "No delay allowed.", level: "B2" },
{ term: "deliberate", meaning: "kasıtlı", hint: "düşünceli", example: "He made a deliberate decision.", level: "B2" },
{ term: "delicious", meaning: "leziz", hint: "çok lezzetli", example: "This cake is delicious.", level: "A1" },
{ term: "deliver", meaning: "teslim etmek", hint: "sunmak", example: "Deliver the package.", level: "B1" },
{ term: "delivery", meaning: "teslimat", hint: "dağıtım", example: "Delivery arrives today.", level: "B2" },
{ term: "demand", meaning: "talep etmek", hint: "gerektirmek", example: "High demand for housing.", level: "B2" },
{ term: "democracy", meaning: "demokrasi", hint: "halk yönetimi", example: "Democracy is important.", level: "B1" },
{ term: "democratic", meaning: "demokratik", hint: "çoğulcu", example: "Democratic election.", level: "B2" },
{ term: "demonstrate", meaning: "göstermek", hint: "kanıtlamak", example: "She demonstrated the method.", level: "B2" },
{ term: "den", meaning: "mağara", hint: "barınak", example: "A lion’s den.", level: "B1" },
{ term: "dentist", meaning: "dişçi", hint: "diş hekimi", example: "Dental appointment.", level: "A2" },
{ term: "deny", meaning: "inkar etmek", hint: "reddetmek", example: "He denies the claims.", level: "B2" },
{ term: "depend", meaning: "bağlı olmak", hint: "güvenmek", example: "Depend on me.", level: "A2" },
{ term: "depress", meaning: "bunaltmak", hint: "vazgeçirmek", example: "The news depresses him.", level: "C1" },
{ term: "depressed", meaning: "üzüntülü", hint: "kasvetli", example: "She is depressed.", level: "B2" },
{ term: "depth", meaning: "derinlik", hint: "yoğunluk", example: "Check the depth.", level: "B2" },
{ term: "describe", meaning: "tanımlamak", hint: "anlatmak", example: "Describe the scene.", level: "A1" },
{ term: "description", meaning: "açıklama", hint: "tanım", example: "Provide a description.", level: "A1" },
{ term: "desert", meaning: "çöl", hint: "terketmek", example: "The desert is vast.", level: "B2" },
{ term: "design", meaning: "tasarlamak", hint: "dizayn etmek", example: "He will design the building.", level: "A1" },
{ term: "desire", meaning: "arzu etmek", hint: "istek", example: "He desires success.", level: "B2" },
{ term: "desk", meaning: "sıra", hint: "ofis masası", example: "Write at your desk.", level: "A1" },
{ term: "desperate", meaning: "çaresiz", hint: "öldüğüm", example: "He’s desperate to win.", level: "B2" },
{ term: "despite", meaning: "rağmen", hint: "karşın", example: "Despite the rain, we went out.", level: "B1" },
{ term: "dessert", meaning: "tatlı", hint: "puding", example: "Have some dessert.", level: "A2" },
{ term: "destination", meaning: "hedef", hint: "varış yeri", example: "Reach your destination.", level: "B1" },
{ term: "destroy", meaning: "yok etmek", hint: "tahrip etmek", example: "The bomb can destroy cities.", level: "A2" },
{ term: "detail", meaning: "ayrıntı", hint: "detay", example: "Detail the report.", level: "A1" },
{ term: "detect", meaning: "tespit etmek", hint: "keşfetmek", example: "Detect the fault.", level: "B2" },
{ term: "detective", meaning: "dedektif", hint: "polis memuru", example: "She is a detective.", level: "A2" },
{ term: "determine", meaning: "belirlemek", hint: "karar vermek", example: "Determine the cause.", level: "B1" },
{ term: "determined", meaning: "kararlı", hint: "azimli", example: "He is determined to succeed.", level: "B1" },
{ term: "develop", meaning: "geliştirmek", hint: "ilerlemek", example: "Develop new skills.", level: "A2" },
{ term: "development", meaning: "gelişim", hint: "ilerleme", example: "Economic development.", level: "B1" },
{ term: "diagram", meaning: "diyagram", hint: "şema", example: "Draw the diagram.", level: "B1" },
{ term: "dialogue", meaning: "diyalog", hint: "konuşma", example: "They had a dialogue.", level: "A1" },
{ term: "diamond", meaning: "elmas", hint: "pırıltı", example: "A diamond ring.", level: "B1" },
{ term: "diary", meaning: "günlük", hint: "ajanda", example: "Keep a diary.", level: "A2" },
{ term: "dictionary", meaning: "sözlük", hint: "rehber", example: "Look it up in the dictionary.", level: "A1" },
{ term: "die", meaning: "ölmek", hint: "poşetlemek", example: "Do not die.", level: "A1" },
{ term: "difference", meaning: "fark", hint: "ayrım", example: "What's the difference?", level: "A1" },
{ term: "different", meaning: "farklı", hint: "başka", example: "They are different people.", level: "A1" },
{ term: "difficult", meaning: "zor", hint: "güç", example: "Math is difficult.", level: "A1" },
{ term: "dig", meaning: "kazmak", hint: "araştırmak", example: "Dig a hole.", level: "B2" },
{ term: "digital", meaning: "sayısal", hint: "dijital", example: "Digital technology.", level: "A2" },
{ term: "dinner", meaning: "akşam yemeği", hint: "yemek", example: "We had dinner.", level: "A1" },
{ term: "direct", meaning: "yönlendirmek", hint: "doğrudan", example: "Direct the actors.", level: "A2" },
{ term: "direction", meaning: "yön", hint: "talimat", example: "Go in this direction.", level: "A2" },
{ term: "directly", meaning: "doğrudan doğruya", hint: "hemen", example: "Speak directly.", level: "B1" },
{ term: "director", meaning: "yönetmen", hint: "düzenleyici", example: "Film director.", level: "A2" },
{ term: "dirt", meaning: "kir", hint: "çamur", example: "Wash off the dirt.", level: "B1" },
{ term: "dirty", meaning: "kirli", hint: "terk etmek", example: "Don't wear dirty shoes.", level: "A1" },
{ term: "disadvantage", meaning: "dezavantaj", hint: "sakınca", example: "List the disadvantages.", level: "B1" },
{ term: "disagree", meaning: "katılmamak", hint: "itiraz etmek", example: "We disagree with that opinion.", level: "A2" },
{ term: "disappear", meaning: "gözden kaybolmak", hint: "kayıp olmak", example: "He will disappear.", level: "A2" },
{ term: "disappointed", meaning: "hayal kırıklığına uğramış", hint: "üzgün", example: "They were disappointed with the result.", level: "B1" },
{ term: "disappointing", meaning: "hayal kırıklığına uğratan", hint: "üzücü", example: "What a disappointing result!", level: "B1" },
{ term: "disaster", meaning: "felaket", hint: "afet", example: "A natural disaster.", level: "A2" },
{ term: "discipline", meaning: "disiplin", hint: "tartışma", example: "Maintain discipline.", level: "B2" },
{ term: "discount", meaning: "indirim", hint: "hesaba katmamak", example: "Offer a discount.", level: "B2" },
{ term: "discover", meaning: "keşfetmek", hint: "bulmak", example: "Discover new lands.", level: "A2" },
{ term: "discovery", meaning: "keşif", hint: "buluntu", example: "Scientific discovery.", level: "A2" },
{ term: "discuss", meaning: "tartışmak", hint: "konuşmak", example: "Discuss the issue.", level: "A1" },
{ term: "discussion", meaning: "tartışma", hint: "sohbet", example: "Have a discussion.", level: "A2" },
{ term: "disease", meaning: "hastalık", hint: "rahatsızlık", example: "Combat the disease.", level: "A2" },
{ term: "dish", meaning: "tabak", hint: "yemek", example: "Wash the dishes.", level: "A1" },
{ term: "dislike", meaning: "nefret etmek", hint: "beğenmemek", example: "I dislike noise.", level: "B1" },
{ term: "dismiss", meaning: "reddetmek", hint: "kovmak", example: "Dismiss the idea.", level: "B2" },
{ term: "display", meaning: "sergilemek", hint: "göstermek", example: "Display the item.", level: "B2" },
{ term: "distance", meaning: "mesafe", hint: "uzaklık", example: "Maintain distance.", level: "A2" },
{ term: "distribute", meaning: "dağıtmak", hint: "yaymak", example: "Distribute the flyers.", level: "B2" },
{ term: "distribution", meaning: "dağılım", hint: "teslimat", example: "Food distribution.", level: "B2" },
{ term: "district", meaning: "bölge", hint: "ilçe", example: "He lives in this district.", level: "B1" },
{ term: "divide", meaning: "bölmek", hint: "ayırmak", example: "Divide the cake.", level: "B1" },
{ term: "division", meaning: "bölüm", hint: "çözünme", example: "Math division.", level: "B2" },
{ term: "divorce", meaning: "boşanma", hint: "ayrı kalmak", example: "They will divorce.", level: "A2" },
{ term: "do", meaning: "yapmak", hint: "soru eki", example: "Do your homework.", level: "A1" },
{ term: "doctor", meaning: "doktor", hint: "hekim", example: "See a doctor.", level: "A1" },
{ term: "document", meaning: "belge", hint: "evrak", example: "Submit the document.", level: "A2" },
{ term: "dog", meaning: "köpek", hint: "sadık", example: "A dog is barking.", level: "A1" },
{ term: "dollar", meaning: "dolar", hint: "para birimi", example: "It costs 5 dollars.", level: "A1" },
{ term: "domestic", meaning: "evcil", hint: "yerel", example: "Domestic flights only.", level: "B2" },
{ term: "dominate", meaning: "egemen olmak", hint: "üstün gelmek", example: "They dominated the game.", level: "B2" },
{ term: "donate", meaning: "bağış yapmak", hint: "verdirmek", example: "Donate to charity.", level: "B1" },
{ term: "door", meaning: "kapı", hint: "giriş", example: "Close the door.", level: "A1" },
{ term: "double", meaning: "iki kat", hint: "çift", example: "Double the recipe.", level: "A2" },
{ term: "doubt", meaning: "şüphe etmek", hint: "kuşku", example: "I doubt that.", level: "B1" },
{ term: "down", meaning: "aşağı", hint: "kapalı", example: "Sit down.", level: "A1" },
{ term: "download", meaning: "indir", hint: "yüklemek", example: "Download the file.", level: "A2" },
{ term: "downstairs", meaning: "alt kat", hint: "aşağıda", example: "Go downstairs.", level: "A1" },
{ term: "downward", meaning: "aşağı doğru", hint: "düşüş", example: "He walked downward.", level: "B2" },
{ term: "dozen", meaning: "on iki", hint: "düzine", example: "A dozen eggs.", level: "B2" },
{ term: "draft", meaning: "taslak", hint: "rüzgar", example: "Draft the letter.", level: "B2" },
{ term: "drag", meaning: "sürüklemek", hint: "çekmek", example: "Drag the box.", level: "B2" },
{ term: "drama", meaning: "drama", hint: "tiyatro", example: "He acts in drama.", level: "A2" },
{ term: "dramatic", meaning: "dramatik", hint: "etkileyici", example: "Dramatic turn of events.", level: "B2" },
{ term: "draw", meaning: "çizmek", hint: "kazanmak", example: "Draw a picture.", level: "A1" },
{ term: "dream", meaning: "rüya", hint: "hayal etmek", example: "I had a dream.", level: "A2" },
{ term: "dress", meaning: "giymek", hint: "giydirmek", example: "She will dress the wound.", level: "A1" },
{ term: "dressed", meaning: "giyinik", hint: "düzeltmek", example: "She is well dressed.", level: "B1" },
{ term: "drink", meaning: "içmek", hint: "içecek", example: "Drink plenty of water.", level: "A1" },
{ term: "drive", meaning: "sürmek", hint: "gitmek", example: "I will drive to work.", level: "A1" },
{ term: "driver", meaning: "sürücü", hint: "şoför", example: "Call a driver.", level: "A1" },
{ term: "driving", meaning: "sürüş", hint: "direksiyon", example: "He takes driving lessons.", level: "A2" }
];

module.exports = wordsData;